#!/usr/bin/env python3
"""
codebase_init_commands.py — CLI command for initial codebase documentation setup.

Creates the docs/repo/codebase/ directory structure and generates initial
codebase documentation for a repository.

This is a one-time setup command, not a workflow. After initial setup,
use sdlc_00_codebase_v1 workflow for periodic sync.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path
from typing import Any


def _p(*parts: str) -> str:
    """Join path parts using forward slashes."""
    return str(Path(*parts))


def _write_text(path: Path, content: str) -> None:
    """Write text content to a file, creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _generate_codebase_inventory(project_root: Path) -> str:
    """Generate initial codebase inventory document."""
    timestamp = dt.datetime.now().isoformat(timespec="seconds")
    
    # Scan repository structure
    python_files = list(project_root.rglob("*.py"))
    md_files = list(project_root.rglob("*.md"))
    toml_files = list(project_root.rglob("*.toml"))
    
    # Filter out common non-source directories
    exclude_dirs = {".venv", "node_modules", "__pycache__", ".git", "archive"}
    python_files = [f for f in python_files if not any(excl in f.parts for excl in exclude_dirs)]
    md_files = [f for f in md_files if not any(excl in f.parts for excl in exclude_dirs)]
    
    content = f"""---
template_id: "SYS-00-CI"
version: "1.0.0"
doc_type: "system"
authority: "workflow-generated"
scan_policy: "include"
scan_reason: "permanent codebase inventory for repository documentation"
layer: "layer3"
platform: "agent-runner-v2"
lifecycle_status: "approved"
generated_at: "{timestamp}"
managed_by: "cli-command"
---

# Codebase Inventory

## Purpose

This document provides an inventory of the repository structure, including
source files, documentation, and configuration files. It serves as the
foundation for codebase documentation.

## Repository Overview

- **Repository Root:** `{project_root}`
- **Generated At:** `{timestamp}`
- **Generated By:** `ukbe-run-agent codebase-init`

## File Statistics

| Category | Count |
|----------|-------|
| Python Files | {len(python_files)} |
| Markdown Files | {len(md_files)} |
| TOML Files | {len(toml_files)} |

## Directory Structure

### Source Code

Python source files are organized under the following directories:

"""
    
    # Group Python files by top-level directory
    dir_counts: dict[str, int] = {}
    for f in python_files:
        rel = f.relative_to(project_root)
        top_dir = rel.parts[0] if len(rel.parts) > 1 else "(root)"
        dir_counts[top_dir] = dir_counts.get(top_dir, 0) + 1
    
    for dir_name, count in sorted(dir_counts.items()):
        content += f"- `{dir_name}/`: {count} files\n"
    
    content += f"""

### Documentation

Markdown documentation files:

"""
    
    # Group markdown files by top-level directory
    md_dir_counts: dict[str, int] = {}
    for f in md_files:
        rel = f.relative_to(project_root)
        top_dir = rel.parts[0] if len(rel.parts) > 1 else "(root)"
        md_dir_counts[top_dir] = md_dir_counts.get(top_dir, 0) + 1
    
    for dir_name, count in sorted(md_dir_counts.items()):
        content += f"- `{dir_name}/`: {count} files\n"
    
    content += f"""

## Key Files

### Configuration

"""
    
    # List key configuration files
    config_files = ["pyproject.toml", "requirements.txt", ".env.example", "README.md"]
    for config_file in config_files:
        config_path = project_root / config_file
        if config_path.exists():
            content += f"- `{config_file}`: Present\n"
        else:
            content += f"- `{config_file}`: Not found\n"
    
    content += """

## Next Steps

This inventory provides a baseline for codebase documentation. Future updates
should be performed using the `sdlc_00_codebase_v1` workflow for periodic sync.
"""
    
    return content


def _generate_codebase_doc_sop(project_root: Path) -> str:
    """Generate codebase documentation SOP."""
    timestamp = dt.datetime.now().isoformat(timespec="seconds")
    
    return f"""---
template_id: "SYS-00-CDS"
version: "1.0.0"
doc_type: "system"
authority: "workflow-generated"
scan_policy: "include"
scan_reason: "permanent codebase documentation standard"
layer: "layer3"
platform: "agent-runner-v2"
lifecycle_status: "approved"
generated_at: "{timestamp}"
managed_by: "cli-command"
---

# Codebase Documentation Standard

## Purpose

This document defines the standard for codebase documentation within the
repository. It establishes conventions for documenting modules, components,
and changes.

## Documentation Structure

Codebase documentation follows a staging pattern under `docs/repo/codebase/`:

- `current/` -- Published stable version (active docs)
  - `00_standards/` - Documentation standards and rules
  - `01_inventory/` - Codebase inventory
  - `02_modules/` - Module-level documentation
  - `03_components/` - Component-level documentation
  - `04_changes/` - Change impact documentation
- `runs/<job_id>/` -- Staging area for in-progress sync operations
- `history/<job_id>/` -- Archived previous versions
- `backups/` -- Pre-sync safety snapshots

## Documentation Rules

### File Naming

- Use lowercase with underscores: `module_name.md`
- Match the Python module name when documenting a module
- Use descriptive names for component documentation

### Frontmatter Requirements

All codebase documentation must include YAML frontmatter with:

- `template_id`: Unique identifier for the document type
- `version`: Document version
- `doc_type`: "system" for codebase docs
- `authority`: "workflow-generated" or "human-authored"
- `scan_policy`: "include" for permanent docs
- `lifecycle_status`: "approved" for active docs

### Content Requirements

- ASCII-only content (no Unicode characters)
- Plain text section headings (no backticks or formatting)
- Clear purpose statement at the beginning
- Structured sections with consistent headings

## Update Triggers

Codebase documentation should be updated when:

1. New modules or components are added
2. Significant architectural changes occur
3. Module interfaces change
4. Component responsibilities shift

## Maintenance

Use `sdlc_00_codebase_v1` workflow for periodic synchronization of codebase
documentation with the actual repository state.
"""


def _generate_codebase_status_rules(project_root: Path) -> str:
    """Generate codebase documentation status rules."""
    timestamp = dt.datetime.now().isoformat(timespec="seconds")
    
    return f"""---
template_id: "SYS-00-CSR"
version: "1.0.0"
doc_type: "system"
authority: "workflow-generated"
scan_policy: "include"
scan_reason: "permanent codebase status rules"
layer: "layer3"
platform: "agent-runner-v2"
lifecycle_status: "approved"
generated_at: "{timestamp}"
managed_by: "cli-command"
---

# Codebase Documentation Status Rules

## Purpose

This document defines the status lifecycle for codebase documentation within
the repository.

## Status Values

Codebase documentation uses the following lifecycle statuses:

| Status | Meaning |
|--------|---------|
| `draft` | Initial version, under review |
| `approved` | Active documentation, reflects current state |
| `superseded` | Replaced by newer version |
| `deprecated` | No longer maintained, kept for reference |

## Status Transitions

```
draft -> approved (after review)
approved -> superseded (when replaced)
approved -> deprecated (when no longer relevant)
```

## Approval Process

Codebase documentation generated by `ukbe-run-agent codebase-init` or
`sdlc_00_codebase_v1` is automatically set to `approved` status, as it
reflects the current state of the repository.

## Validation Rules

All codebase documentation must:

1. Have valid YAML frontmatter
2. Include required metadata fields
3. Use ASCII-only content
4. Follow the documentation structure defined in CODEBASE_DOC_SOP.md
"""


def main(argv: list[str] | None = None) -> int:
    """Main entry point for codebase-init command."""
    parser = argparse.ArgumentParser(
        description="Initialize codebase documentation structure for a repository."
    )
    parser.add_argument(
        "--project-root",
        default="",
        help="Repository root directory. Defaults to current directory.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing codebase documentation.",
    )
    
    args = parser.parse_args(argv)
    
    project_root = Path(args.project_root).resolve() if args.project_root else Path.cwd().resolve()
    
    if not project_root.exists():
        print(f"Error: Project root does not exist: {project_root}", file=sys.stderr)
        return 1
    
    if not project_root.is_dir():
        print(f"Error: Project root is not a directory: {project_root}", file=sys.stderr)
        return 1
    
    # Define codebase documentation paths
    codebase_root = project_root / "docs" / "repo" / "codebase" / "current"
    standards_dir = codebase_root / "00_standards"
    inventory_dir = codebase_root / "01_inventory"
    modules_dir = codebase_root / "02_modules"
    components_dir = codebase_root / "03_components"
    changes_dir = codebase_root / "04_changes"
    
    # Check if codebase docs already exist
    if codebase_root.exists() and not args.force:
        existing_files = list(codebase_root.rglob("*.md"))
        if existing_files:
            print(f"Warning: Codebase documentation already exists at {codebase_root}", file=sys.stderr)
            print(f"Found {len(existing_files)} existing markdown files.", file=sys.stderr)
            print("Use --force to overwrite.", file=sys.stderr)
            return 1
    
    # Create directory structure
    print(f"Creating codebase documentation structure at {codebase_root}...")
    
    for dir_path in [standards_dir, inventory_dir, modules_dir, components_dir, changes_dir]:
        dir_path.mkdir(parents=True, exist_ok=True)
        print(f"  Created: {dir_path.relative_to(project_root)}")
    
    # Generate initial documentation
    print("\nGenerating initial documentation...")
    
    # Codebase inventory
    inventory_path = inventory_dir / "codebase_inventory.md"
    inventory_content = _generate_codebase_inventory(project_root)
    _write_text(inventory_path, inventory_content)
    print(f"  Generated: {inventory_path.relative_to(project_root)}")
    
    # Codebase documentation SOP
    sop_path = standards_dir / "CODEBASE_DOC_SOP.md"
    sop_content = _generate_codebase_doc_sop(project_root)
    _write_text(sop_path, sop_content)
    print(f"  Generated: {sop_path.relative_to(project_root)}")
    
    # Codebase status rules
    rules_path = standards_dir / "CODEBASE_DOC_STATUS_RULES.md"
    rules_content = _generate_codebase_status_rules(project_root)
    _write_text(rules_path, rules_content)
    print(f"  Generated: {rules_path.relative_to(project_root)}")
    
    # Generate summary
    result = {
        "status": "success",
        "project_root": str(project_root),
        "codebase_root": str(codebase_root),
        "files_created": [
            str(inventory_path.relative_to(project_root)),
            str(sop_path.relative_to(project_root)),
            str(rules_path.relative_to(project_root)),
        ],
        "directories_created": [
            str(standards_dir.relative_to(project_root)),
            str(inventory_dir.relative_to(project_root)),
            str(modules_dir.relative_to(project_root)),
            str(components_dir.relative_to(project_root)),
            str(changes_dir.relative_to(project_root)),
        ],
        "next_steps": [
            "Review generated documentation",
            "Run sdlc_00_codebase_v1 workflow for periodic sync",
            "Start using sdlc_10_requirement_v1 for initiative intake",
        ],
    }
    
    print("\n" + "=" * 60)
    print("Codebase initialization complete!")
    print("=" * 60)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
