from __future__ import annotations

"""Artifact path catalogs and compatibility mappings.

This module owns path-discovery helpers and reference-file catalogs so active
runtime callers do not need to import the compatibility shim in constants.py.
"""

from .artifact_keys import (
    ARTIFACT_KEY_ARCHITECTURE_FLOW,
    ARTIFACT_KEY_ARCHITECTURE_SITE_INDEX,
    ARTIFACT_KEY_ARCHITECTURE_SITE_MANIFEST,
    ARTIFACT_KEY_CODEBASE_COMPONENT_TEMPLATE,
    ARTIFACT_KEY_CODEBASE_DOC_SOP,
    ARTIFACT_KEY_CODEBASE_DOC_STATUS_RULES,
    ARTIFACT_KEY_CODEBASE_INVENTORY,
    ARTIFACT_KEY_CODEBASE_INVENTORY_TEMPLATE,
    ARTIFACT_KEY_CODEBASE_MODULE_TEMPLATE,
    ARTIFACT_KEY_CODEBASE_TEMPLATE_REGISTRY,
    ARTIFACT_KEY_DELIVERY_AGENT_EXECUTOR,
    ARTIFACT_KEY_DELIVERY_AGENT_IMPL_PLANNER,
    ARTIFACT_KEY_DELIVERY_AGENT_MEMORY_MANAGER,
    ARTIFACT_KEY_DELIVERY_AGENT_PLANNER,
    ARTIFACT_KEY_DELIVERY_AGENT_REVIEWER,
    ARTIFACT_KEY_DELIVERY_AGENT_TASK_DECOMPOSER,
    ARTIFACT_KEY_DELIVERY_AGENTS,
    ARTIFACT_KEY_DELIVERY_FOLDER_MAP,
    ARTIFACT_KEY_DELIVERY_IMPL_TEMPLATE,
    ARTIFACT_KEY_DELIVERY_INITIATIVE_TEMPLATE,
    ARTIFACT_KEY_DELIVERY_MEMORY_TEMPLATE,
    ARTIFACT_KEY_DELIVERY_PLAN_TEMPLATE,
    ARTIFACT_KEY_DELIVERY_REVIEW_TEMPLATE,
    ARTIFACT_KEY_DELIVERY_SOP,
    ARTIFACT_KEY_DELIVERY_STATUS_RULES,
    ARTIFACT_KEY_DELIVERY_TASK_GRAPH_TEMPLATE,
    ARTIFACT_KEY_DELIVERY_TASK_TEMPLATE,
    ARTIFACT_KEY_DELIVERY_TEMPLATE_REGISTRY,
    ARTIFACT_KEY_DELIVERY_VALIDATION_TEMPLATE,
    ARTIFACT_KEY_DEVELOPER_SITE_INDEX,
    ARTIFACT_KEY_DEVELOPER_SITE_MARKDOWN,
    ARTIFACT_KEY_DEVELOPER_SITE_PDF,
    ARTIFACT_KEY_EXISTING_REPO_WORKFLOW_SOP,
    ARTIFACT_KEY_FAILURE_MODES,
    ARTIFACT_KEY_INTEGRATION_MAP,
    ARTIFACT_KEY_OPERATOR_SITE_INDEX,
    ARTIFACT_KEY_OPERATOR_SITE_MARKDOWN,
    ARTIFACT_KEY_OPERATOR_SITE_PDF,
    ARTIFACT_KEY_PROJECT_ANALYSIS,
    ARTIFACT_KEY_STAKEHOLDER_SITE_INDEX,
    ARTIFACT_KEY_STAKEHOLDER_SITE_MARKDOWN,
    ARTIFACT_KEY_STAKEHOLDER_SITE_PDF,
    ARTIFACT_KEY_SYSTEM_DOCS_INDEX,
    ARTIFACT_KEY_SYSTEM_DOC_STANDARD,
    ARTIFACT_KEY_TESTER_SITE_INDEX,
    ARTIFACT_KEY_TESTER_SITE_MARKDOWN,
    ARTIFACT_KEY_TESTER_SITE_PDF,
    ARTIFACT_KEY_USER_SITE_INDEX,
    ARTIFACT_KEY_USER_SITE_MARKDOWN,
    ARTIFACT_KEY_USER_SITE_PDF,
    ARTIFACT_KEY_WORKFLOW_SOP,
)
from .constants_legacy_backup_20260717 import (
    ARTIFACT_PATH_ARCHITECTURE_FLOW,
    ARTIFACT_PATH_CODEBASE_COMPONENT_TEMPLATE,
    ARTIFACT_PATH_CODEBASE_DOC_SOP,
    ARTIFACT_PATH_CODEBASE_DOC_STATUS_RULES,
    ARTIFACT_PATH_CODEBASE_INVENTORY,
    ARTIFACT_PATH_CODEBASE_INVENTORY_TEMPLATE,
    ARTIFACT_PATH_CODEBASE_MODULE_TEMPLATE,
    ARTIFACT_PATH_CODEBASE_TEMPLATE_REGISTRY,
    ARTIFACT_PATH_DELIVERY_AGENT_EXECUTOR,
    ARTIFACT_PATH_DELIVERY_AGENT_IMPL_PLANNER,
    ARTIFACT_PATH_DELIVERY_AGENT_MEMORY_MANAGER,
    ARTIFACT_PATH_DELIVERY_AGENT_PLANNER,
    ARTIFACT_PATH_DELIVERY_AGENT_REVIEWER,
    ARTIFACT_PATH_DELIVERY_AGENT_TASK_DECOMPOSER,
    ARTIFACT_PATH_DELIVERY_AGENTS,
    ARTIFACT_PATH_DELIVERY_FOLDER_MAP,
    ARTIFACT_PATH_DELIVERY_IMPL_TEMPLATE,
    ARTIFACT_PATH_DELIVERY_INITIATIVE_TEMPLATE,
    ARTIFACT_PATH_DELIVERY_MEMORY_TEMPLATE,
    ARTIFACT_PATH_DELIVERY_PLAN_TEMPLATE,
    ARTIFACT_PATH_DELIVERY_REVIEW_TEMPLATE,
    ARTIFACT_PATH_DELIVERY_STATUS_RULES,
    ARTIFACT_PATH_DELIVERY_TASK_GRAPH_TEMPLATE,
    ARTIFACT_PATH_DELIVERY_TASK_TEMPLATE,
    ARTIFACT_PATH_DELIVERY_TEMPLATE_REGISTRY,
    ARTIFACT_PATH_DELIVERY_VALIDATION_TEMPLATE,
    ARTIFACT_PATH_DOCUMENTATION_STANDARD,
    ARTIFACT_PATH_EXISTING_REPO_WORKFLOW_SOP,
    ARTIFACT_PATH_FAILURE_MODES,
    ARTIFACT_PATH_INTEGRATION_MAP,
    ARTIFACT_PATH_PROJECT_ANALYSIS,
    ARTIFACT_PATH_README,
    ARTIFACT_PATH_WORKFLOW_SOP,
    REFERENCE_FILES,
    legacy_artifact_paths,
)
from .path_primitives import (
    EXT_PDF,
    FILENAME_SITE_CONTENT_MD,
    FILENAME_SITE_INDEX_BASE,
    FILENAME_SITE_INDEX_HTML,
    FILENAME_SITE_MANIFEST_JSON,
    developer_site_rel,
    docs_site_rel,
    operator_site_rel,
    placeholder,
    stakeholder_site_rel,
    tester_site_rel,
    user_site_rel,
)
from .workflow_path_contracts import resolve_workflow_output_paths


def delivery_scaffold_docs() -> dict[str, str]:
    return {
        ARTIFACT_KEY_PROJECT_ANALYSIS: ARTIFACT_PATH_PROJECT_ANALYSIS,
        ARTIFACT_KEY_DELIVERY_SOP: ARTIFACT_PATH_WORKFLOW_SOP,
        ARTIFACT_KEY_DELIVERY_STATUS_RULES: ARTIFACT_PATH_DELIVERY_STATUS_RULES,
        ARTIFACT_KEY_DELIVERY_VALIDATION_TEMPLATE: ARTIFACT_PATH_DELIVERY_VALIDATION_TEMPLATE,
        ARTIFACT_KEY_DELIVERY_TEMPLATE_REGISTRY: ARTIFACT_PATH_DELIVERY_TEMPLATE_REGISTRY,
        ARTIFACT_KEY_DELIVERY_INITIATIVE_TEMPLATE: ARTIFACT_PATH_DELIVERY_INITIATIVE_TEMPLATE,
        ARTIFACT_KEY_DELIVERY_PLAN_TEMPLATE: ARTIFACT_PATH_DELIVERY_PLAN_TEMPLATE,
        ARTIFACT_KEY_DELIVERY_TASK_GRAPH_TEMPLATE: ARTIFACT_PATH_DELIVERY_TASK_GRAPH_TEMPLATE,
        ARTIFACT_KEY_DELIVERY_TASK_TEMPLATE: ARTIFACT_PATH_DELIVERY_TASK_TEMPLATE,
        ARTIFACT_KEY_DELIVERY_IMPL_TEMPLATE: ARTIFACT_PATH_DELIVERY_IMPL_TEMPLATE,
        ARTIFACT_KEY_DELIVERY_REVIEW_TEMPLATE: ARTIFACT_PATH_DELIVERY_REVIEW_TEMPLATE,
        ARTIFACT_KEY_DELIVERY_MEMORY_TEMPLATE: ARTIFACT_PATH_DELIVERY_MEMORY_TEMPLATE,
        ARTIFACT_KEY_DELIVERY_AGENTS: ARTIFACT_PATH_DELIVERY_AGENTS,
        ARTIFACT_KEY_DELIVERY_AGENT_PLANNER: ARTIFACT_PATH_DELIVERY_AGENT_PLANNER,
        ARTIFACT_KEY_DELIVERY_AGENT_TASK_DECOMPOSER: ARTIFACT_PATH_DELIVERY_AGENT_TASK_DECOMPOSER,
        ARTIFACT_KEY_DELIVERY_AGENT_IMPL_PLANNER: ARTIFACT_PATH_DELIVERY_AGENT_IMPL_PLANNER,
        ARTIFACT_KEY_DELIVERY_AGENT_EXECUTOR: ARTIFACT_PATH_DELIVERY_AGENT_EXECUTOR,
        ARTIFACT_KEY_DELIVERY_AGENT_REVIEWER: ARTIFACT_PATH_DELIVERY_AGENT_REVIEWER,
        ARTIFACT_KEY_DELIVERY_AGENT_MEMORY_MANAGER: ARTIFACT_PATH_DELIVERY_AGENT_MEMORY_MANAGER,
        ARTIFACT_KEY_CODEBASE_DOC_SOP: ARTIFACT_PATH_CODEBASE_DOC_SOP,
        ARTIFACT_KEY_CODEBASE_DOC_STATUS_RULES: ARTIFACT_PATH_CODEBASE_DOC_STATUS_RULES,
        ARTIFACT_KEY_CODEBASE_TEMPLATE_REGISTRY: ARTIFACT_PATH_CODEBASE_TEMPLATE_REGISTRY,
        ARTIFACT_KEY_CODEBASE_INVENTORY_TEMPLATE: ARTIFACT_PATH_CODEBASE_INVENTORY_TEMPLATE,
        ARTIFACT_KEY_CODEBASE_MODULE_TEMPLATE: ARTIFACT_PATH_CODEBASE_MODULE_TEMPLATE,
        ARTIFACT_KEY_CODEBASE_COMPONENT_TEMPLATE: ARTIFACT_PATH_CODEBASE_COMPONENT_TEMPLATE,
        ARTIFACT_KEY_CODEBASE_INVENTORY: ARTIFACT_PATH_CODEBASE_INVENTORY,
        ARTIFACT_KEY_DELIVERY_FOLDER_MAP: ARTIFACT_PATH_DELIVERY_FOLDER_MAP,
        ARTIFACT_KEY_EXISTING_REPO_WORKFLOW_SOP: ARTIFACT_PATH_EXISTING_REPO_WORKFLOW_SOP,
    }


def audience_site_artifacts() -> dict[str, str]:
    return {
        ARTIFACT_KEY_ARCHITECTURE_SITE_INDEX: docs_site_rel(FILENAME_SITE_INDEX_HTML),
        ARTIFACT_KEY_ARCHITECTURE_SITE_MANIFEST: docs_site_rel(FILENAME_SITE_MANIFEST_JSON),
        ARTIFACT_KEY_STAKEHOLDER_SITE_MARKDOWN: stakeholder_site_rel(FILENAME_SITE_CONTENT_MD),
        ARTIFACT_KEY_DEVELOPER_SITE_MARKDOWN: developer_site_rel(FILENAME_SITE_CONTENT_MD),
        ARTIFACT_KEY_OPERATOR_SITE_MARKDOWN: operator_site_rel(FILENAME_SITE_CONTENT_MD),
        ARTIFACT_KEY_TESTER_SITE_MARKDOWN: tester_site_rel(FILENAME_SITE_CONTENT_MD),
        ARTIFACT_KEY_USER_SITE_MARKDOWN: user_site_rel(FILENAME_SITE_CONTENT_MD),
        ARTIFACT_KEY_STAKEHOLDER_SITE_INDEX: stakeholder_site_rel(FILENAME_SITE_INDEX_HTML),
        ARTIFACT_KEY_DEVELOPER_SITE_INDEX: developer_site_rel(FILENAME_SITE_INDEX_HTML),
        ARTIFACT_KEY_OPERATOR_SITE_INDEX: operator_site_rel(FILENAME_SITE_INDEX_HTML),
        ARTIFACT_KEY_TESTER_SITE_INDEX: tester_site_rel(FILENAME_SITE_INDEX_HTML),
        ARTIFACT_KEY_USER_SITE_INDEX: user_site_rel(FILENAME_SITE_INDEX_HTML),
        ARTIFACT_KEY_STAKEHOLDER_SITE_PDF: stakeholder_site_rel(f"{FILENAME_SITE_INDEX_BASE}{EXT_PDF}"),
        ARTIFACT_KEY_DEVELOPER_SITE_PDF: developer_site_rel(f"{FILENAME_SITE_INDEX_BASE}{EXT_PDF}"),
        ARTIFACT_KEY_OPERATOR_SITE_PDF: operator_site_rel(f"{FILENAME_SITE_INDEX_BASE}{EXT_PDF}"),
        ARTIFACT_KEY_TESTER_SITE_PDF: tester_site_rel(f"{FILENAME_SITE_INDEX_BASE}{EXT_PDF}"),
        ARTIFACT_KEY_USER_SITE_PDF: user_site_rel(f"{FILENAME_SITE_INDEX_BASE}{EXT_PDF}"),
    }


def architecture_site_pages() -> dict[str, str]:
    return {
        docs_site_rel(FILENAME_SITE_INDEX_HTML): "Documentation Hub",
        docs_site_rel(FILENAME_SITE_MANIFEST_JSON): "Manifest",
    }


def stakeholder_site_pages() -> dict[str, str]:
    return {
        stakeholder_site_rel(FILENAME_SITE_INDEX_HTML): "Stakeholder Documentation",
        stakeholder_site_rel(FILENAME_SITE_MANIFEST_JSON): "Manifest",
    }


def developer_site_pages() -> dict[str, str]:
    return {
        developer_site_rel(FILENAME_SITE_INDEX_HTML): "Developer Documentation",
        developer_site_rel(FILENAME_SITE_MANIFEST_JSON): "Manifest",
    }


def operator_site_pages() -> dict[str, str]:
    return {
        operator_site_rel(FILENAME_SITE_INDEX_HTML): "Operator Documentation",
        operator_site_rel(FILENAME_SITE_MANIFEST_JSON): "Manifest",
    }


def tester_site_pages() -> dict[str, str]:
    return {
        tester_site_rel(FILENAME_SITE_INDEX_HTML): "Tester Documentation",
        tester_site_rel(FILENAME_SITE_MANIFEST_JSON): "Manifest",
    }


def user_site_pages() -> dict[str, str]:
    return {
        user_site_rel(FILENAME_SITE_INDEX_HTML): "User Documentation",
        user_site_rel(FILENAME_SITE_MANIFEST_JSON): "Manifest",
    }


def get_master_docs_output_paths(job_id: str = "{job_id}", mode: str = "{mode}") -> dict[str, str]:
    return resolve_workflow_output_paths(
        template_group="00_repo_master_docs_bootstrap_v1",
        job_id=job_id,
        mode=mode,
    )


def known_artifact_paths() -> dict[str, str]:
    paths: dict[str, str] = {}
    paths.update(get_master_docs_output_paths())
    paths.update(delivery_scaffold_docs())
    paths[ARTIFACT_KEY_INTEGRATION_MAP] = ARTIFACT_PATH_INTEGRATION_MAP
    paths[ARTIFACT_KEY_FAILURE_MODES] = ARTIFACT_PATH_FAILURE_MODES
    paths[ARTIFACT_KEY_ARCHITECTURE_FLOW] = ARTIFACT_PATH_ARCHITECTURE_FLOW
    paths.update(audience_site_artifacts())
    return paths


PROMPT_LITERAL_ALIASES: dict[str, str] = {
    ARTIFACT_PATH_README: ARTIFACT_KEY_SYSTEM_DOCS_INDEX,
    ARTIFACT_PATH_DOCUMENTATION_STANDARD: ARTIFACT_KEY_SYSTEM_DOC_STANDARD,
}


def prompt_literal_substitutions() -> dict[str, str]:
    substitutions = {
        literal_path: placeholder(alias_key)
        for literal_path, alias_key in PROMPT_LITERAL_ALIASES.items()
    }
    substitutions.update(
        {
            literal_path: placeholder(artifact_key)
            for artifact_key, literal_path in known_artifact_paths().items()
        }
    )
    substitutions.update(
        {
            legacy_path: placeholder(artifact_key)
            for artifact_key, legacy_paths in legacy_artifact_paths().items()
            for legacy_path in legacy_paths
        }
    )
    return substitutions
