from __future__ import annotations

"""
template_groups.py — Artifact keys and template group definitions for agent_runner_v2.

Related: IMPL-20260422-04
"""

from pathlib import Path
from typing import Any, Dict


def _p(*parts: str) -> str:
    return str(Path(*parts))


REFERENCE_FILES: Dict[str, str] = {
    "AGENTS_MD": _p("docs", "delivery", "08_agents", "AGENTS.md"),
    "DELIVERY_STATUS_RULES": _p("docs", "delivery", "00_templates", "DELIVERY_STATUS_RULES_v1.md"),
    "WORKFLOW_SOP": _p("docs", "delivery", "00_templates", "WORKFLOW_SOP_v1.md"),
}


ARTIFACT_KEYS = [
    "DRAFT_INIT_FILE",
    "PRE_INIT_FILE",
    "INIT_FILE",
    "PLAN_FILE",
    "TASK_GRAPH_FILE",
    "TASK_FILE",
    "IMPL_FILE",
    "REVIEW_FILE",
    "VALIDATION_FILE",
    "CONTEXT_PACK_FILE",
    "IMAGE_FILE",
    "IMAGE_FOLDER",
    "IMAGE_DESC_FOLDER",
    "IMAGE_CSV_JSON",
    "IMAGE_CSV_CSV",
    "IMAGE_CSV_SUBMIT_RESULT",
    # Delivery scaffold artifacts
    "PROJECT_CONTEXT_FILE",
    "PROJECT_ANALYSIS",
    "DELIVERY_SOP",
    "DELIVERY_STATUS_RULES",
    "DELIVERY_TEMPLATE_REGISTRY",
    "DELIVERY_INITIATIVE_TEMPLATE",
    "DELIVERY_PLAN_TEMPLATE",
    "DELIVERY_TASK_GRAPH_TEMPLATE",
    "DELIVERY_TASK_TEMPLATE",
    "DELIVERY_IMPL_TEMPLATE",
    "DELIVERY_REVIEW_TEMPLATE",
    "DELIVERY_MEMORY_TEMPLATE",
    "DELIVERY_AGENTS_MD",
    "DELIVERY_AGENT_PLANNER",
    "DELIVERY_AGENT_TASK_DECOMPOSER",
    "DELIVERY_AGENT_IMPL_PLANNER",
    "DELIVERY_AGENT_EXECUTOR",
    "DELIVERY_AGENT_REVIEWER",
    "DELIVERY_AGENT_MEMORY_MANAGER",
    "DELIVERY_FOLDER_MAP",
]


TEMPLATE_GROUPS: Dict[str, Dict[str, Any]] = {
    "initiative_intake_v1": {
        "job_prefix": "PREINIT",
        "job_init_step": "pre_init",
        "job_init_inputs": ["DRAFT_INIT_FILE"],
        "default_max_rejects": 2,
        "steps": ["pre_init", "review_pre_init", "refine_pre_init", "promote_init"],
        "step_configs": {
            "pre_init": {
                "prompt_file": _p("prompts", "initiative_intake_v1", "01_pre_init.txt"),
                "required_inputs": ["DRAFT_INIT_FILE"],
                "produces": ["PRE_INIT_FILE"],
                "produced_document_status": {"artifact": "PRE_INIT_FILE", "required_status": "draft"},
                "immutable_inputs": ["DRAFT_INIT_FILE"],
                "validate_init_traceability": {
                    "artifact": "PRE_INIT_FILE",
                    "source_artifact": "DRAFT_INIT_FILE",
                    "generated_by": "pre_init",
                },
                "result_meta_key": "PRE_INIT_FILE",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_pre_init": {
                "prompt_file": _p("prompts", "initiative_intake_v1", "02_review_pre_init.txt"),
                "required_inputs": ["PRE_INIT_FILE"],
                "preflight_status_check": {"artifact": "PRE_INIT_FILE", "required_status": "draft"},
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_pre_init",
                    "artifact": "PRE_INIT_FILE",
                    "max_iterations": 2,
                    "exhausted_failure_code": "PRE_INIT_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "requires_human_approval_after": True,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "codex",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_pre_init": {
                "prompt_file": _p("prompts", "initiative_intake_v1", "03_refine_pre_init.txt"),
                "required_inputs": ["PRE_INIT_FILE", "REVIEW_FILE"],
                "preflight_status_check": {"artifact": "PRE_INIT_FILE", "required_status": "changes_requested"},
                "produces": ["PRE_INIT_FILE"],
                "target_artifact": "PRE_INIT_FILE",
                "edit_mode": "in_place",
                "loop_returns_to": "review_pre_init",
                "result_meta_key": "PRE_INIT_FILE",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "promote_init": {
                "action": "promote_init",
                "required_inputs": ["PRE_INIT_FILE"],
                "produces": ["INIT_FILE"],
                "result_meta_key": "INIT_FILE",
            },
        },
    },
    "delivery_planning_v1": {
        "job_prefix": "PLAN",
        "job_init_step": "planner",
        "job_init_inputs": ["INIT_FILE"],
        "default_max_rejects": 2,
        "max_planning_attempts": 5,
        "steps": [
            "planner",
            "review_planner",
            "refine_plan",
            "replan_plan",
            "task_graph",
            "review_task_graph",
            "refine_task_graph",
            "replan_task_graph",
        ],
        "step_configs": {
            "planner": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "02_planner.txt"),
                "required_inputs": ["INIT_FILE"],
                "preflight_status_check": {"artifact": "INIT_FILE", "required_status": "Approved"},
                "produces": ["PLAN_FILE"],
                "produced_document_status": {"artifact": "PLAN_FILE", "required_status": "draft"},
                "result_meta_key": "PLAN_FILE",
                "template_ref": {
                    "type": "02_plan",
                    "template_artifact_key": "DELIVERY_PLAN_TEMPLATE",
                    "template_fallback_path": _p("prompts", "delivery_planning_v1", "02_planner.txt"),
                    "required_sections": [
                        "Plan Objective", "Strategy Overview", "Task Breakdown",
                        "Scope Mapping", "Risks", "Deliverables", "Acceptance Criteria",
                    ],
                    "required_metadata_fields": ["Doc Type", "Plan ID", "Initiative ID", "Status"],
                },
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_planner": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "03_review_planner.txt"),
                "required_inputs": ["INIT_FILE", "PLAN_FILE"],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_plan",
                    "artifact": "PLAN_FILE",
                    "max_iterations": 2,
                    "exhausted_failure_code": "PLAN_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "on_exhaust_replan": {
                    "step": "replan_plan",
                    "artifact": "PLAN_FILE",
                    "max_replans": 1,
                    "terminal_failure_code": "PLAN_REPLAN_EXHAUSTED",
                },
                "requires_human_approval_after": True,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_plan": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "03_refine_plan.txt"),
                "required_inputs": ["INIT_FILE", "PLAN_FILE", "REVIEW_FILE"],
                "produces": ["PLAN_FILE"],
                "target_artifact": "PLAN_FILE",
                "edit_mode": "in_place",
                "loop_returns_to": "review_planner",
                "result_meta_key": "PLAN_FILE",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "replan_plan": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "03_replan_plan.txt"),
                "required_inputs": ["INIT_FILE", "PLAN_FILE", "REVIEW_FILE"],
                "produces": ["PLAN_FILE"],
                "target_artifact": "PLAN_FILE",
                "edit_mode": "in_place",
                "replan_returns_to": "review_planner",
                "result_meta_key": "PLAN_FILE",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "task_graph": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "04_task_graph.txt"),
                "required_inputs": ["PLAN_FILE"],
                "preflight_status_check": {"artifact": "PLAN_FILE", "required_status": "Approved"},
                "produces": ["TASK_GRAPH_FILE"],
                "produced_document_status": {"artifact": "TASK_GRAPH_FILE", "required_status": "draft"},
                "result_meta_key": "TASK_GRAPH_FILE",
                "template_ref": {
                    "type": "02b_task_graph",
                    "template_artifact_key": "DELIVERY_TASK_GRAPH_TEMPLATE",
                    "required_sections": [
                        "Task Graph Objective", "Task Graph",
                        "Execution Flow", "Success Criteria",
                    ],
                    "required_metadata_fields": ["Doc Type", "Task Graph ID", "Plan ID", "Initiative ID", "Status"],
                },
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_task_graph": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "05_review_task_graph.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE"],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_task_graph",
                    "artifact": "TASK_GRAPH_FILE",
                    "max_iterations": 2,
                    "exhausted_failure_code": "TASK_GRAPH_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "on_exhaust_replan": {
                    "step": "replan_task_graph",
                    "artifact": "TASK_GRAPH_FILE",
                    "max_replans": 1,
                    "terminal_failure_code": "TASK_GRAPH_REPLAN_EXHAUSTED",
                },
                "requires_human_approval_after": True,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_task_graph": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "05_refine_task_graph.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE", "REVIEW_FILE"],
                "produces": ["TASK_GRAPH_FILE"],
                "target_artifact": "TASK_GRAPH_FILE",
                "edit_mode": "in_place",
                "loop_returns_to": "review_task_graph",
                "result_meta_key": "TASK_GRAPH_FILE",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "replan_task_graph": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "05_replan_task_graph.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE", "REVIEW_FILE"],
                "produces": ["TASK_GRAPH_FILE"],
                "target_artifact": "TASK_GRAPH_FILE",
                "edit_mode": "in_place",
                "replan_returns_to": "review_task_graph",
                "result_meta_key": "TASK_GRAPH_FILE",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "task": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "06_task.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE"],
                "preflight_status_check": {"artifact": "TASK_GRAPH_FILE", "required_status": "Approved"},
                "produces": ["TASK_FILE"],
                "produced_document_status": {"artifact": "TASK_FILE", "required_status": "draft"},
                "result_meta_key": "TASK_FILE",
                "template_ref": {
                    "type": "03_task",
                    "template_artifact_key": "DELIVERY_TASK_TEMPLATE",
                    "required_sections": [
                        "Objective", "Inputs", "Outputs",
                        "Execution Steps", "Validation Criteria",
                    ],
                    "required_metadata_fields": ["Doc Type", "Task ID", "Plan ID", "Title", "Status"],
                },
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_task": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "07_review_task.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE", "TASK_FILE"],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_task",
                    "artifact": "TASK_FILE",
                    "max_iterations": 2,
                    "exhausted_failure_code": "TASK_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "on_exhaust_replan": {
                    "step": "replan_task",
                    "artifact": "TASK_FILE",
                    "max_replans": 1,
                    "terminal_failure_code": "TASK_REPLAN_EXHAUSTED",
                },
                "requires_human_approval_after": True,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_task": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "07_refine_task.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE", "TASK_FILE", "REVIEW_FILE"],
                "produces": ["TASK_FILE"],
                "target_artifact": "TASK_FILE",
                "edit_mode": "in_place",
                "loop_returns_to": "review_task",
                "result_meta_key": "TASK_FILE",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "replan_task": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "07_replan_task.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE", "TASK_FILE", "REVIEW_FILE"],
                "produces": ["TASK_FILE"],
                "target_artifact": "TASK_FILE",
                "edit_mode": "in_place",
                "replan_returns_to": "review_task",
                "result_meta_key": "TASK_FILE",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
        },
    },
    "task_execution_v1": {
        "job_prefix": "EXEC",
        "job_init_step": "task",
        "job_init_inputs": [],
        "default_max_rejects": 2,
        "steps": ["task", "review_task", "refine_task", "impl", "review_impl", "refine_impl", "executor", "validator"],
        "step_configs": {
            "task": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "06_task.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE"],
                "preflight_status_check": {"artifact": "TASK_GRAPH_FILE", "required_status": "Approved"},
                "produces": ["TASK_FILE"],
                "produced_document_status": {"artifact": "TASK_FILE", "required_status": "draft"},
                "result_meta_key": "TASK_FILE",
                "template_ref": {
                    "type": "03_task",
                    "template_artifact_key": "DELIVERY_TASK_TEMPLATE",
                    "required_sections": [
                        "Objective", "Inputs", "Outputs",
                        "Execution Steps", "Validation Criteria",
                    ],
                    "required_metadata_fields": ["Doc Type", "Task ID", "Plan ID", "Title", "Status"],
                },
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_task": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "07_review_task.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE", "TASK_FILE"],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_task",
                    "artifact": "TASK_FILE",
                    "max_iterations": 2,
                    "exhausted_failure_code": "TASK_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "requires_human_approval_after": True,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_task": {
                "prompt_file": _p("prompts", "delivery_planning_v1", "07_refine_task.txt"),
                "required_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE", "TASK_FILE", "REVIEW_FILE"],
                "produces": ["TASK_FILE"],
                "target_artifact": "TASK_FILE",
                "edit_mode": "in_place",
                "loop_returns_to": "review_task",
                "result_meta_key": "TASK_FILE",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "impl": {
                "prompt_file": _p("prompts", "task_execution_v1", "08_impl_task.txt"),
                "required_inputs": ["TASK_FILE"],
                "optional_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE"],
                "produces": ["IMPL_FILE"],
                "produced_document_status": {"artifact": "IMPL_FILE", "required_status": "draft"},
                "preflight_status_check": {"artifact": "TASK_FILE", "required_status": "Approved"},
                "result_meta_key": "IMPL_FILE",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_impl": {
                "prompt_file": _p("prompts", "task_execution_v1", "09_review_impl_task.txt"),
                "required_inputs": ["TASK_FILE", "IMPL_FILE"],
                "optional_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE"],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step":           "refine_impl",
                    "artifact":       "IMPL_FILE",
                    "max_iterations": 2,
                    "exhausted_failure_code": "IMPL_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "requires_human_approval_after": True,
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_impl": {
                "prompt_file": _p("prompts", "task_execution_v1", "09_refine_impl.txt"),
                "required_inputs": ["TASK_FILE", "IMPL_FILE", "REVIEW_FILE"],
                "optional_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE"],
                "produces": ["IMPL_FILE"],
                "target_artifact": "IMPL_FILE",
                "edit_mode": "in_place",
                "loop_returns_to": "review_impl",
                "result_meta_key": "IMPL_FILE",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "executor": {
                "prompt_file": _p("prompts", "task_execution_v1", "10_executor.txt"),
                "required_inputs": ["TASK_FILE", "IMPL_FILE"],
                "optional_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE"],
                "produces": [],
                "max_rejects": 1,
                # executor modifies IMPL_FILE in-place; writes meta.json alongside it
                "result_meta_key": "IMPL_FILE",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "validator": {
                "prompt_file": _p("prompts", "task_execution_v1", "11_validate.txt"),
                "required_inputs": ["TASK_FILE", "IMPL_FILE"],
                "optional_inputs": ["PLAN_FILE", "TASK_GRAPH_FILE"],
                "produces": ["VALIDATION_FILE"],
                "on_reject_refine": {
                    "step": "refine_impl",
                    "artifact": "IMPL_FILE",
                    "max_iterations": 2,
                    "exhausted_failure_code": "VALIDATION_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "requires_human_approval_after": True,
                # validator writes to VALIDATION_FILE_PATH; meta.json at VALIDATION_FILE_METAJSON
                "result_meta_key": "VALIDATION_FILE",
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
        },
    },
    "image_csv_gen_v1": {
        "job_prefix": "IMGCSV",
        "job_init_step": "extract_desc",
        "job_init_inputs": ["IMAGE_FOLDER"],
        "default_max_rejects": 2,
        "reference_files": {},
        "steps": ["extract_desc", "gen_prompts", "review_prompts", "refine_prompts", "submit_prompts"],
        "step_configs": {
            "extract_desc": {
                "prompt_file": _p("prompts", "image_csv_gen_v1", "01_extract_desc.txt"),
                "required_inputs": ["IMAGE_FOLDER"],
                "produces": ["IMAGE_DESC_FOLDER"],
                "produced_document_status": {"artifact": "IMAGE_DESC_FOLDER", "required_status": "draft"},
                "result_meta_key": "IMAGE_DESC_FOLDER",
                "coder": {"default": "qwen", "allowed": ["qwen", "codex"]},
            },
            "gen_prompts": {
                "prompt_file": _p("prompts", "image_csv_gen_v1", "02_gen_prompts.txt"),
                "required_inputs": ["IMAGE_FOLDER"],
                "produces": ["IMAGE_CSV_JSON", "IMAGE_CSV_CSV"],
                "produced_document_status": {"artifact": "IMAGE_CSV_JSON", "required_status": "draft"},
                "result_meta_key": "IMAGE_CSV_JSON",
                "coder": {"default": "qwen", "allowed": ["qwen", "codex"]},
            },
            "review_prompts": {
                "prompt_file": _p("prompts", "image_csv_gen_v1", "03_review_prompts.txt"),
                "required_inputs": ["IMAGE_CSV_JSON"],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_prompts",
                    "artifact": "IMAGE_CSV_JSON",
                    "max_iterations": 2,
                    "exhausted_failure_code": "PROMPT_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "requires_human_approval_after": True,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "qwen",
                    "allowed": ["qwen", "codex"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_prompts": {
                "prompt_file": _p("prompts", "image_csv_gen_v1", "04_refine_prompts.txt"),
                "required_inputs": ["IMAGE_FOLDER", "IMAGE_CSV_JSON", "REVIEW_FILE"],
                "produces": ["IMAGE_CSV_JSON", "IMAGE_CSV_CSV"],
                "target_artifact": "IMAGE_CSV_JSON",
                "edit_mode": "in_place",
                "loop_returns_to": "review_prompts",
                "result_meta_key": "IMAGE_CSV_JSON",
                "coder": {"default": "qwen", "allowed": ["qwen", "codex"]},
            },
            "submit_prompts": {
                "required_inputs": ["IMAGE_CSV_JSON"],
                "produces": ["IMAGE_CSV_SUBMIT_RESULT"],
                "result_meta_key": "IMAGE_CSV_SUBMIT_RESULT",
                "action": "submit_comfyui",
            },
        },
    },
    "image_csv_gen_v2": {
        "job_prefix": "IMGCSV",
        "job_init_step": "extract_desc",
        "job_init_inputs": ["IMAGE_FOLDER"],
        "default_max_rejects": 2,
        "reference_files": {},
        "steps": ["extract_desc", "gen_prompts", "submit_prompts"],
        "step_configs": {
            "extract_desc": {
                "prompt_file": _p("prompts", "image_csv_gen_v2", "01_extract_desc.txt"),
                "required_inputs": ["IMAGE_FOLDER"],
                "produces": ["IMAGE_DESC_FOLDER"],
                "produced_document_status": {"artifact": "IMAGE_DESC_FOLDER", "required_status": "draft"},
                "result_meta_key": "IMAGE_DESC_FOLDER",
                "coder": {"default": "qwen", "allowed": ["qwen", "codex", "claude"]},
            },
            "gen_prompts": {
                "prompt_file": _p("prompts", "image_csv_gen_v2", "02_gen_prompts.txt"),
                "required_inputs": ["IMAGE_FOLDER"],
                "produces": ["IMAGE_CSV_JSON", "IMAGE_CSV_CSV"],
                "produced_document_status": {"artifact": "IMAGE_CSV_JSON", "required_status": "draft"},
                "result_meta_key": "IMAGE_CSV_JSON",
                "coder": {"default": "qwen", "allowed": ["qwen", "codex", "claude"]},
            },
            "review_prompts": {
                "prompt_file": _p("prompts", "image_csv_gen_v2", "03_review_prompts.txt"),
                "required_inputs": ["IMAGE_CSV_JSON"],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_prompts",
                    "artifact": "IMAGE_CSV_JSON",
                    "max_iterations": 2,
                    "exhausted_failure_code": "PROMPT_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "requires_human_approval_after": True,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "qwen",
                    "allowed": ["qwen", "codex", "claude"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_prompts": {
                "prompt_file": _p("prompts", "image_csv_gen_v2", "04_refine_prompts.txt"),
                "required_inputs": ["IMAGE_FOLDER", "IMAGE_CSV_JSON", "REVIEW_FILE"],
                "produces": ["IMAGE_CSV_JSON", "IMAGE_CSV_CSV"],
                "target_artifact": "IMAGE_CSV_JSON",
                "edit_mode": "in_place",
                "loop_returns_to": "review_prompts",
                "result_meta_key": "IMAGE_CSV_JSON",
                "coder": {"default": "qwen", "allowed": ["qwen", "codex", "claude"]},
            },
            "submit_prompts": {
                "required_inputs": ["IMAGE_CSV_JSON"],
                "produces": ["IMAGE_CSV_SUBMIT_RESULT"],
                "result_meta_key": "IMAGE_CSV_SUBMIT_RESULT",
                "action": "submit_comfyui",
            },
        },
    },
    "delivery_scaffold_v1": {
        "job_prefix": "SCAFFOLD",
        "job_init_step": "project_analysis",
        "job_init_inputs": [],  # Auto-discovers AI context files — no seed required
        "reference_files": {},
        "default_max_rejects": 2,
        "steps": [
            "project_analysis",
            "generate_sop",
            "review_sop",
            "refine_sop",
            "replan_sop",
            "generate_templates",
            "review_templates",
            "refine_templates",
            "generate_agents",
            "review_agents",
            "refine_agents",
            "validate_delivery_docs",
        ],
        "step_configs": {
            "project_analysis": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "01_project_analysis.txt"),
                # Auto-discovers AI context files — no required inputs
                "produces": ["PROJECT_ANALYSIS"],
                "result_meta_key": "PROJECT_ANALYSIS",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "generate_sop": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "02_generate_sop.txt"),
                "required_inputs": ["PROJECT_ANALYSIS"],
                "produces": ["DELIVERY_SOP", "DELIVERY_STATUS_RULES"],
                "produced_document_status": {"artifact": "DELIVERY_SOP", "required_status": "draft"},
                "result_meta_key": "DELIVERY_SOP",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_sop": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "03_review_sop.txt"),
                "required_inputs": ["PROJECT_ANALYSIS", "DELIVERY_SOP", "DELIVERY_STATUS_RULES"],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_sop",
                    "artifact": "DELIVERY_SOP",
                    "max_iterations": 2,
                    "exhausted_failure_code": "SOP_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "on_exhaust_replan": {
                    "step": "replan_sop",
                    "artifact": "DELIVERY_SOP",
                    "max_iterations": 1,
                    "exhausted_failure_code": "SOP_REPLAN_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "requires_human_approval_after": False,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_sop": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "05_refine_sop.txt"),
                "required_inputs": ["PROJECT_ANALYSIS", "DELIVERY_SOP", "DELIVERY_STATUS_RULES", "REVIEW_FILE"],
                "produces": ["DELIVERY_SOP", "DELIVERY_STATUS_RULES"],
                "target_artifact": "DELIVERY_SOP",
                "edit_mode": "in_place",
                "loop_returns_to": "review_sop",
                "result_meta_key": "DELIVERY_SOP",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "replan_sop": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "05_replan_sop.txt"),
                "required_inputs": ["PROJECT_ANALYSIS", "DELIVERY_SOP", "DELIVERY_STATUS_RULES", "REVIEW_FILE"],
                "produces": ["DELIVERY_SOP", "DELIVERY_STATUS_RULES"],
                "target_artifact": "DELIVERY_SOP",
                "edit_mode": "in_place",
                "replan_returns_to": "generate_sop",
                "result_meta_key": "DELIVERY_SOP",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "generate_templates": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "03_generate_templates.txt"),
                "required_inputs": ["PROJECT_ANALYSIS"],
                "produces": [
                    "DELIVERY_TEMPLATE_REGISTRY",
                    "DELIVERY_INITIATIVE_TEMPLATE",
                    "DELIVERY_PLAN_TEMPLATE",
                    "DELIVERY_TASK_GRAPH_TEMPLATE",
                    "DELIVERY_TASK_TEMPLATE",
                    "DELIVERY_IMPL_TEMPLATE",
                    "DELIVERY_REVIEW_TEMPLATE",
                    "DELIVERY_MEMORY_TEMPLATE",
                ],
                "result_meta_key": "DELIVERY_TEMPLATE_REGISTRY",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_templates": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "06_review_templates.txt"),
                "required_inputs": [
                    "PROJECT_ANALYSIS",
                    "DELIVERY_TEMPLATE_REGISTRY",
                    "DELIVERY_INITIATIVE_TEMPLATE",
                    "DELIVERY_PLAN_TEMPLATE",
                    "DELIVERY_TASK_GRAPH_TEMPLATE",
                    "DELIVERY_TASK_TEMPLATE",
                    "DELIVERY_IMPL_TEMPLATE",
                    "DELIVERY_REVIEW_TEMPLATE",
                    "DELIVERY_MEMORY_TEMPLATE",
                ],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_templates",
                    "artifact": "DELIVERY_TEMPLATE_REGISTRY",
                    "max_iterations": 2,
                    "exhausted_failure_code": "TEMPLATE_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "requires_human_approval_after": False,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_templates": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "06_refine_templates.txt"),
                "required_inputs": [
                    "PROJECT_ANALYSIS",
                    "DELIVERY_TEMPLATE_REGISTRY",
                    "DELIVERY_INITIATIVE_TEMPLATE",
                    "DELIVERY_PLAN_TEMPLATE",
                    "DELIVERY_TASK_GRAPH_TEMPLATE",
                    "DELIVERY_TASK_TEMPLATE",
                    "DELIVERY_IMPL_TEMPLATE",
                    "DELIVERY_REVIEW_TEMPLATE",
                    "DELIVERY_MEMORY_TEMPLATE",
                    "REVIEW_FILE",
                ],
                "produces": [
                    "DELIVERY_TEMPLATE_REGISTRY",
                    "DELIVERY_INITIATIVE_TEMPLATE",
                    "DELIVERY_PLAN_TEMPLATE",
                    "DELIVERY_TASK_GRAPH_TEMPLATE",
                    "DELIVERY_TASK_TEMPLATE",
                    "DELIVERY_IMPL_TEMPLATE",
                    "DELIVERY_REVIEW_TEMPLATE",
                    "DELIVERY_MEMORY_TEMPLATE",
                ],
                "target_artifact": "DELIVERY_TEMPLATE_REGISTRY",
                "edit_mode": "in_place",
                "loop_returns_to": "review_templates",
                "result_meta_key": "DELIVERY_TEMPLATE_REGISTRY",
                "coder": {"default": "qwen", "allowed": ["claude", "codex", "qwen"]},
            },
            "generate_agents": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "04_generate_agents.txt"),
                "required_inputs": ["PROJECT_ANALYSIS", "DELIVERY_SOP", "DELIVERY_STATUS_RULES"],
                "produces": [
                    "DELIVERY_AGENTS_MD",
                    "DELIVERY_AGENT_PLANNER",
                    "DELIVERY_AGENT_TASK_DECOMPOSER",
                    "DELIVERY_AGENT_IMPL_PLANNER",
                    "DELIVERY_AGENT_EXECUTOR",
                    "DELIVERY_AGENT_REVIEWER",
                    "DELIVERY_AGENT_MEMORY_MANAGER",
                ],
                "result_meta_key": "DELIVERY_AGENTS_MD",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "review_agents": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "08_review_agents.txt"),
                "required_inputs": [
                    "PROJECT_ANALYSIS",
                    "DELIVERY_SOP",
                    "DELIVERY_STATUS_RULES",
                    "DELIVERY_AGENTS_MD",
                    "DELIVERY_AGENT_PLANNER",
                    "DELIVERY_AGENT_TASK_DECOMPOSER",
                    "DELIVERY_AGENT_IMPL_PLANNER",
                    "DELIVERY_AGENT_EXECUTOR",
                    "DELIVERY_AGENT_REVIEWER",
                    "DELIVERY_AGENT_MEMORY_MANAGER",
                ],
                "produces": ["REVIEW_FILE"],
                "on_reject_refine": {
                    "step": "refine_agents",
                    "artifact": "DELIVERY_AGENTS_MD",
                    "max_iterations": 2,
                    "exhausted_failure_code": "AGENT_REFINEMENT_EXHAUSTED",
                    "exhausted_failure_class": "HUMAN_RETRY_REQUIRED",
                },
                "requires_human_approval_after": False,
                "result_meta_key_from_context": "REVIEW_FILE_SUGGESTED",
                "coder": {
                    "default": "claude",
                    "allowed": ["claude", "codex", "qwen"],
                    "must_differ_from_previous_step": False,
                },
            },
            "refine_agents": {
                "prompt_file": _p("prompts", "delivery_scaffold_v1", "07_refine_agents.txt"),
                "required_inputs": [
                    "PROJECT_ANALYSIS",
                    "DELIVERY_SOP",
                    "DELIVERY_STATUS_RULES",
                    "DELIVERY_AGENTS_MD",
                    "DELIVERY_AGENT_PLANNER",
                    "DELIVERY_AGENT_TASK_DECOMPOSER",
                    "DELIVERY_AGENT_IMPL_PLANNER",
                    "DELIVERY_AGENT_EXECUTOR",
                    "DELIVERY_AGENT_REVIEWER",
                    "DELIVERY_AGENT_MEMORY_MANAGER",
                    "REVIEW_FILE",
                ],
                "produces": [
                    "DELIVERY_AGENTS_MD",
                    "DELIVERY_AGENT_PLANNER",
                    "DELIVERY_AGENT_TASK_DECOMPOSER",
                    "DELIVERY_AGENT_IMPL_PLANNER",
                    "DELIVERY_AGENT_EXECUTOR",
                    "DELIVERY_AGENT_REVIEWER",
                    "DELIVERY_AGENT_MEMORY_MANAGER",
                ],
                "target_artifact": "DELIVERY_AGENTS_MD",
                "edit_mode": "in_place",
                "loop_returns_to": "review_agents",
                "result_meta_key": "DELIVERY_AGENTS_MD",
                "coder": {"default": "claude", "allowed": ["claude", "codex", "qwen"]},
            },
            "validate_delivery_docs": {
                "required_inputs": [
                    "DELIVERY_SOP",
                    "DELIVERY_STATUS_RULES",
                    "DELIVERY_TEMPLATE_REGISTRY",
                    "DELIVERY_INITIATIVE_TEMPLATE",
                    "DELIVERY_PLAN_TEMPLATE",
                    "DELIVERY_TASK_GRAPH_TEMPLATE",
                    "DELIVERY_TASK_TEMPLATE",
                    "DELIVERY_IMPL_TEMPLATE",
                    "DELIVERY_REVIEW_TEMPLATE",
                    "DELIVERY_MEMORY_TEMPLATE",
                    "DELIVERY_AGENTS_MD",
                    "DELIVERY_AGENT_PLANNER",
                    "DELIVERY_AGENT_TASK_DECOMPOSER",
                    "DELIVERY_AGENT_IMPL_PLANNER",
                    "DELIVERY_AGENT_EXECUTOR",
                    "DELIVERY_AGENT_REVIEWER",
                    "DELIVERY_AGENT_MEMORY_MANAGER",
                ],
                "produces": ["DELIVERY_FOLDER_MAP"],
                "result_meta_key": "DELIVERY_FOLDER_MAP",
                "action": "validate_delivery_docs",
            },
        },
    },
}
