"""Domain actions for text_summarizer_ayz.

Auto-generated by AGB v3. Implements domain-specific action functions.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from agent_runner_v2.action_result import ActionResult
from agent_runner_v2.workflow_packages.actions import action


@action("parse_input_document")
def parse_input_document(*, context, state, step_cfg, project_root):
    """Read source document, detect format, extract text, write PARSED_DOCUMENT."""
    artifacts = state.get("artifacts", {})
    project_root = Path(project_root)

    # Resolve input path
    source_path_str = context.get("SOURCE_DOCUMENT_FILE")
    if not source_path_str:
        return ActionResult(
            status="REJECTED",
            remark="SOURCE_DOCUMENT_FILE not found in context",
            artifacts={},
            reject_code="MISSING_INPUT",
        )

    source_path = Path(source_path_str)
    if not source_path.is_absolute():
        source_path = project_root / source_path

    # Validate file exists
    if not source_path.exists():
        return ActionResult(
            status="REJECTED",
            remark=f"Source document not found: {source_path}",
            artifacts={},
            reject_code="FILE_NOT_FOUND",
        )

    if not source_path.is_file():
        return ActionResult(
            status="REJECTED",
            remark=f"Path is not a regular file: {source_path}",
            artifacts={},
            reject_code="FILE_NOT_FOUND",
        )

    # Detect format by extension
    ext = source_path.suffix.lower()
    extracted_text = None

    try:
        if ext in (".txt", ".md"):
            # Read as UTF-8 text
            try:
                extracted_text = source_path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                # Fallback to latin-1
                try:
                    extracted_text = source_path.read_text(encoding="latin-1")
                except Exception as e:
                    return ActionResult(
                        status="REJECTED",
                        remark=f"Failed to read file with any encoding: {e}",
                        artifacts={},
                        reject_code="PARSE_ERROR",
                    )

        elif ext == ".pdf":
            # Extract text using PyPDF2
            try:
                from PyPDF2 import PdfReader

                reader = PdfReader(str(source_path))
                pages_text = []
                for page in reader.pages:
                    page_text = page.extract_text()
                    if page_text:
                        pages_text.append(page_text)
                extracted_text = "\n\n".join(pages_text)
            except ImportError:
                return ActionResult(
                    status="REJECTED",
                    remark="PyPDF2 library not available for PDF parsing",
                    artifacts={},
                    reject_code="PARSE_ERROR",
                )
            except Exception as e:
                return ActionResult(
                    status="REJECTED",
                    remark=f"PDF parsing failed: {e}",
                    artifacts={},
                    reject_code="PARSE_ERROR",
                )

        elif ext == ".docx":
            # Extract text using python-docx
            try:
                from docx import Document

                doc = Document(str(source_path))
                paragraphs = [para.text for para in doc.paragraphs]
                extracted_text = "\n\n".join(paragraphs)
            except ImportError:
                return ActionResult(
                    status="REJECTED",
                    remark="python-docx library not available for DOCX parsing",
                    artifacts={},
                    reject_code="PARSE_ERROR",
                )
            except Exception as e:
                return ActionResult(
                    status="REJECTED",
                    remark=f"DOCX parsing failed: {e}",
                    artifacts={},
                    reject_code="PARSE_ERROR",
                )

        else:
            return ActionResult(
                status="REJECTED",
                remark=f"Unsupported file format: {ext}. Supported: .txt, .md, .pdf, .docx",
                artifacts={},
                reject_code="INVALID_FORMAT",
            )

    except OSError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"File I/O error: {e}",
            artifacts={},
            reject_code="FILE_NOT_FOUND",
        )

    # Validate extracted text is non-empty
    if not extracted_text or not extracted_text.strip():
        return ActionResult(
            status="REJECTED",
            remark="Extracted text is empty",
            artifacts={},
            reject_code="EMPTY_CONTENT",
        )

    if len(extracted_text.strip()) < 10:
        return ActionResult(
            status="REJECTED",
            remark=f"Extracted text too short ({len(extracted_text.strip())} chars, minimum 10)",
            artifacts={},
            reject_code="EMPTY_CONTENT",
        )

    # Normalize whitespace: strip excessive whitespace but preserve paragraph breaks
    lines = extracted_text.splitlines()
    normalized_lines = []
    for line in lines:
        stripped = line.strip()
        normalized_lines.append(stripped)

    # Join and collapse multiple blank lines into paragraph breaks
    text = "\n".join(normalized_lines)
    # Collapse 3+ consecutive newlines into 2 (preserving paragraph breaks)
    while "\n\n\n" in text:
        text = text.replace("\n\n\n", "\n\n")
    text = text.strip()

    # Detect language (simple heuristic: check for CJK characters, then assume English)
    language = "en"
    sample = text[:500]
    cjk_count = sum(1 for c in sample if "\u4e00" <= c <= "\u9fff" or "\u3040" <= c <= "\u309f" or "\u30a0" <= c <= "\u30ff")
    if cjk_count > len(sample) * 0.1:
        if any("\u4e00" <= c <= "\u9fff" for c in sample):
            language = "zh"
        elif any("\u3040" <= c <= "\u309f" for c in sample) or any("\u30a0" <= c <= "\u30ff" for c in sample):
            language = "ja"
        else:
            language = "ko"

    # Write to PARSED_DOCUMENT
    output_path_str = context.get("PARSED_DOCUMENT")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="PARSED_DOCUMENT output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )

    output_path = Path(output_path_str)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write normalized text with language metadata header
    content = text
    output_path.write_text(content, encoding="utf-8")

    return ActionResult(
        status="APPROVED",
        remark=f"Parsed {ext} document ({len(text)} chars, detected language: {language}). Written to PARSED_DOCUMENT.",
        artifacts={"PARSED_DOCUMENT": str(output_path)},
    )


@action("render_output_document")
def render_output_document(*, context, state, step_cfg, project_root):
    """Render TRANSFORMED_CONTENT JSON as prose summary OUTPUT_FILE. Validates 20% word count constraint."""
    artifacts = state.get("artifacts", {})
    project_root = Path(project_root)

    # Resolve TRANSFORMED_CONTENT path
    transformed_path_str = context.get("TRANSFORMED_CONTENT")
    if not transformed_path_str:
        return ActionResult(
            status="REJECTED",
            remark="TRANSFORMED_CONTENT not found in context",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    transformed_path = Path(transformed_path_str)
    if not transformed_path.exists():
        return ActionResult(
            status="REJECTED",
            remark=f"TRANSFORMED_CONTENT file not found: {transformed_path}",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    # Load JSON content
    try:
        content_text = transformed_path.read_text(encoding="utf-8")
        transformed_data = json.loads(content_text)
    except json.JSONDecodeError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"TRANSFORMED_CONTENT is not valid JSON: {e}",
            artifacts={},
            reject_code="INVALID_STRUCTURE",
        )
    except OSError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to read TRANSFORMED_CONTENT: {e}",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    # Validate JSON structure
    if not isinstance(transformed_data, dict):
        return ActionResult(
            status="REJECTED",
            remark="TRANSFORMED_CONTENT JSON must be an object",
            artifacts={},
            reject_code="INVALID_STRUCTURE",
        )

    if "summary_text" not in transformed_data:
        return ActionResult(
            status="REJECTED",
            remark="TRANSFORMED_CONTENT JSON missing required field: summary_text",
            artifacts={},
            reject_code="MISSING_FIELD",
        )

    summary_text = transformed_data["summary_text"]
    if not isinstance(summary_text, str) or not summary_text.strip():
        return ActionResult(
            status="REJECTED",
            remark="summary_text field is empty or not a string",
            artifacts={},
            reject_code="EMPTY_CONTENT",
        )

    # Resolve PARSED_DOCUMENT for word count comparison
    parsed_path_str = context.get("PARSED_DOCUMENT")
    if not parsed_path_str:
        return ActionResult(
            status="REJECTED",
            remark="PARSED_DOCUMENT not found in context (needed for word count validation)",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    parsed_path = Path(parsed_path_str)
    if not parsed_path.exists():
        return ActionResult(
            status="REJECTED",
            remark=f"PARSED_DOCUMENT file not found: {parsed_path}",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    # Count words
    try:
        original_text = parsed_path.read_text(encoding="utf-8")
    except OSError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to read PARSED_DOCUMENT: {e}",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    original_word_count = len(original_text.split())
    summary_word_count = len(summary_text.split())

    # Validate word count constraint: summary <= 20% of original
    if original_word_count > 0:
        ratio = summary_word_count / original_word_count
        if ratio > 0.20:
            return ActionResult(
                status="REJECTED",
                remark=f"Summary word count ({summary_word_count}) exceeds 20% of original ({original_word_count}). Ratio: {ratio:.2%}",
                artifacts={},
                reject_code="WORD_COUNT_EXCEEDED",
            )
    # If original is 0 words, skip the check (edge case)

    # Write to OUTPUT_FILE
    output_path_str = context.get("OUTPUT_FILE")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="OUTPUT_FILE output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )

    output_path = Path(output_path_str)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_path.write_text(summary_text, encoding="utf-8")

    return ActionResult(
        status="APPROVED",
        remark=f"Rendered prose summary: {summary_word_count}/{original_word_count} words ({summary_word_count / max(original_word_count, 1):.2%} compression). Written to OUTPUT_FILE.",
        artifacts={"OUTPUT_FILE": str(output_path)},
    )
