"""Domain actions for codebase_intelligence.

Auto-generated by AGB v3. Implements domain-specific action functions.
"""
from __future__ import annotations

import ast
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agent_runner_v2.action_result import ActionResult
from agent_runner_v2.workflow_packages.actions import action


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_text_safe(path: Path, max_chars: int | None = None) -> str | None:
    """Read a file as UTF-8 text, falling back to latin-1. Returns None if binary."""
    try:
        text = path.read_text(encoding="utf-8")
        if max_chars is not None:
            return text[:max_chars]
        return text
    except UnicodeDecodeError:
        try:
            text = path.read_text(encoding="latin-1")
            if max_chars is not None:
                return text[:max_chars]
            return text
        except Exception:
            return None
    except OSError:
        return None


def _extract_title_from_markdown(text: str) -> str:
    """Extract the first heading from markdown content."""
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()
    return ""


def _has_docstring(content: str) -> bool:
    """Check if a Python file has a module-level docstring."""
    try:
        tree = ast.parse(content)
        if tree.body and isinstance(tree.body[0], ast.Expr):
            if isinstance(tree.body[0].value, (ast.Constant,)):
                return isinstance(tree.body[0].value.value, str)
    except SyntaxError:
        pass
    return False


def _is_binary_file(path: Path) -> bool:
    """Heuristic check for binary files."""
    try:
        chunk = path.read_bytes()[:8192]
        if b"\x00" in chunk:
            return True
        return False
    except OSError:
        return True


_TEXT_EXTENSIONS = {
    ".md", ".txt", ".toml", ".yaml", ".yml", ".json",
    ".py", ".cfg", ".ini", ".rst", ".csv", ".xml",
    ".html", ".css", ".js", ".ts", ".sh", ".bat",
    ".lock", ".gitignore", ".env", ".properties",
}


def _resolve_package_path(relative_path: str) -> str:
    """Convert a relative file path to a Python package path.

    E.g. 'agent_runner_v2/workflow/__init__.py' -> 'agent_runner_v2.workflow'
    E.g. 'agent_runner_v2/workflow/runner.py' -> 'agent_runner_v2.workflow.runner'
    """
    p = Path(relative_path)
    parts = list(p.parts)
    if parts[-1] == "__init__.py":
        parts = parts[:-1]
    else:
        parts[-1] = parts[-1].rsplit(".py", 1)[0]
    return ".".join(parts)


def _resolve_relative_import(
    level: int,
    import_module: str | None,
    file_package: str,
) -> str | None:
    """Resolve a relative import to an absolute module name.

    Args:
        level: Number of leading dots (1 for '.', 2 for '..', etc.)
        import_module: The module portion after 'from .X import' (can be None)
        file_package: The fully qualified package of the importing file

    Returns:
        Fully qualified module name, or None if unresolvable.
    """
    parts = file_package.split(".")
    # level=1 means relative to current package
    # level=2 means relative to parent package, etc.
    go_up = level - 1
    if go_up > len(parts):
        return None
    if go_up > 0:
        base_parts = parts[:-go_up]
    else:
        base_parts = parts[:]

    base = ".".join(base_parts)
    if import_module:
        if base:
            return f"{base}.{import_module}"
        return import_module
    return base if base else None


def _detect_cycles(adjacency: dict[str, list[str]]) -> list[list[str]]:
    """Detect all unique cycles in a directed graph using DFS.

    Returns list of cycles, where each cycle is a list of module names
    with the first and last being the same node.
    """
    visited: set[str] = set()
    rec_stack: set[str] = set()
    path: list[str] = []
    cycles: list[list[str]] = []
    seen_cycle_keys: set[str] = set()

    def _dfs(node: str) -> None:
        visited.add(node)
        rec_stack.add(node)
        path.append(node)

        for neighbor in adjacency.get(node, []):
            if neighbor not in visited:
                _dfs(neighbor)
            elif neighbor in rec_stack:
                # Found a cycle - extract it
                cycle_start = path.index(neighbor)
                cycle = path[cycle_start:] + [neighbor]
                # Normalize cycle for dedup: rotate so smallest element is first
                min_idx = cycle[:-1].index(min(cycle[:-1]))
                normalized = cycle[min_idx:-1] + cycle[:min_idx] + [cycle[min_idx]]
                key = "->".join(normalized[:-1])
                if key not in seen_cycle_keys:
                    seen_cycle_keys.add(key)
                    cycles.append(normalized)

        path.pop()
        rec_stack.discard(node)

    for node in sorted(adjacency.keys()):
        if node not in visited:
            _dfs(node)

    return cycles


def _validate_markdown_content(content: str) -> dict[str, Any]:
    """Validate a Markdown file's structure and evidence backing.

    Returns a dict with validation results.
    """
    result = {
        "exists": True,
        "has_headings": False,
        "has_evidence": False,
        "self_contained": True,
    }

    # Check for headings
    heading_pattern = re.compile(r"^#{1,6}\s+.+", re.MULTILINE)
    if heading_pattern.search(content):
        result["has_headings"] = True

    # Check for evidence: file paths, inline code, or fenced code blocks
    file_path_pattern = re.compile(r"[`\"\'](?:[\w./\\-]+\.(?:py|md|json|yaml|toml|txt))")
    inline_code_pattern = re.compile(r"`[^`]+`")
    fenced_code_pattern = re.compile(r"```")

    if (file_path_pattern.search(content)
            or inline_code_pattern.search(content)
            or fenced_code_pattern.search(content)):
        result["has_evidence"] = True

    # Check for self-containment: no dangling references
    dangling_patterns = [
        r"see above(?!.*(?:heading|section|table|figure))",
        r"see previous section",
        r"as mentioned before(?!.*(?:heading|section|table|figure))",
        r"described earlier(?!.*(?:heading|section|table|figure))",
    ]
    for pat in dangling_patterns:
        if re.search(pat, content, re.IGNORECASE):
            result["self_contained"] = False
            break

    return result


# ---------------------------------------------------------------------------
# Action: scan_codebase_files
# ---------------------------------------------------------------------------

@action("scan_codebase_files")
def scan_codebase_files(*, context: dict, state: dict, step_cfg: dict, project_root: Any) -> ActionResult:
    """Walk codebase docs and source directories, produce a structured JSON inventory."""
    project_root = Path(project_root)

    # Resolve input paths
    docs_dir_str = context.get("CODEBASE_DOCS_DIR")
    source_dir_str = context.get("SOURCE_CODE_DIR")

    if not docs_dir_str or not source_dir_str:
        missing = []
        if not docs_dir_str:
            missing.append("CODEBASE_DOCS_DIR")
        if not source_dir_str:
            missing.append("SOURCE_CODE_DIR")
        return ActionResult(
            status="REJECTED",
            remark=f"Missing input paths in context: {', '.join(missing)}",
            artifacts={},
            reject_code="MISSING_INPUT",
        )

    docs_dir = Path(docs_dir_str)
    source_dir = Path(source_dir_str)

    # Validate directories exist
    for d, name in [(docs_dir, "CODEBASE_DOCS_DIR"), (source_dir, "SOURCE_CODE_DIR")]:
        if not d.exists():
            return ActionResult(
                status="REJECTED",
                remark=f"Directory not found for {name}: {d}",
                artifacts={},
                reject_code="DIRECTORY_NOT_FOUND",
            )
        if not d.is_dir():
            return ActionResult(
                status="REJECTED",
                remark=f"Path is not a directory for {name}: {d}",
                artifacts={},
                reject_code="DIRECTORY_NOT_FOUND",
            )

    # Resolve output path
    output_path_str = context.get("CODEBASE_INVENTORY")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="CODEBASE_INVENTORY output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )
    output_path = Path(output_path_str)

    try:
        # Scan documentation files
        docs_files: list[dict[str, Any]] = []
        try:
            for file_path in sorted(docs_dir.rglob("*")):
                if not file_path.is_file():
                    continue
                rel_path = str(file_path.relative_to(docs_dir))
                ext = file_path.suffix.lower()
                size = file_path.stat().st_size

                # Determine file category from parent directory
                parts = file_path.relative_to(docs_dir).parts
                file_category = parts[0] if len(parts) > 1 else "root"

                # Read preview for text files
                preview = ""
                if _is_binary_file(file_path):
                    pass  # binary: metadata only
                elif ext in _TEXT_EXTENSIONS or ext == "":
                    content = _read_text_safe(file_path, max_chars=500)
                    if content is not None:
                        preview = content
                    # else: unreadable, keep preview empty

                docs_files.append({
                    "relative_path": rel_path,
                    "absolute_path": str(file_path),
                    "filename": file_path.name,
                    "extension": ext,
                    "size_bytes": size,
                    "file_category": file_category,
                    "preview": preview,
                })
        except OSError as e:
            return ActionResult(
                status="REJECTED",
                remark=f"File system error scanning docs directory: {e}",
                artifacts={},
                reject_code="FILE_SYSTEM_ERROR",
            )

        # Scan source code files
        source_files: list[dict[str, Any]] = []
        packages_set: set[str] = set()
        try:
            for file_path in sorted(source_dir.rglob("*")):
                if not file_path.is_file():
                    continue
                rel_path = str(file_path.relative_to(source_dir))
                ext = file_path.suffix.lower()
                size = file_path.stat().st_size

                if ext == ".py":
                    # Parse Python file
                    content = _read_text_safe(file_path)
                    line_count = 0
                    has_docstring = False
                    module_name = file_path.stem

                    pkg_path = _resolve_package_path(rel_path)
                    if pkg_path:
                        packages_set.add(pkg_path.rsplit(".", 1)[0] if file_path.name != "__init__.py" else pkg_path)

                    if content is not None:
                        line_count = content.count("\n") + (1 if content and not content.endswith("\n") else 0)
                        has_docstring = _has_docstring(content)

                    source_files.append({
                        "relative_path": rel_path,
                        "absolute_path": str(file_path),
                        "filename": file_path.name,
                        "extension": ext,
                        "size_bytes": size,
                        "module_name": module_name,
                        "package_path": pkg_path,
                        "is_init": file_path.name == "__init__.py",
                        "line_count": line_count,
                        "has_docstring": has_docstring,
                        "file_type": "python",
                    })
                else:
                    # Non-Python file in source tree
                    source_files.append({
                        "relative_path": rel_path,
                        "absolute_path": str(file_path),
                        "filename": file_path.name,
                        "extension": ext,
                        "size_bytes": size,
                        "module_name": "",
                        "package_path": "",
                        "is_init": False,
                        "line_count": 0,
                        "has_docstring": False,
                        "file_type": "non_python",
                    })
        except OSError as e:
            return ActionResult(
                status="REJECTED",
                remark=f"File system error scanning source directory: {e}",
                artifacts={},
                reject_code="FILE_SYSTEM_ERROR",
            )

        # Check non-empty codebase
        if not docs_files and not source_files:
            return ActionResult(
                status="REJECTED",
                remark="No files found in either docs or source directory",
                artifacts={},
                reject_code="EMPTY_CODEBASE",
            )

        # Build summary metadata
        file_type_dist: dict[str, int] = {}
        for f in docs_files:
            ext = f["extension"] or "(none)"
            file_type_dist[ext] = file_type_dist.get(ext, 0) + 1
        for f in source_files:
            ext = f["extension"] or "(none)"
            file_type_dist[ext] = file_type_dist.get(ext, 0) + 1

        python_modules = [f for f in source_files if f.get("file_type") == "python"]

        inventory = {
            "metadata": {
                "scan_timestamp": datetime.now(timezone.utc).isoformat(),
                "docs_root": str(docs_dir),
                "source_root": str(source_dir),
                "total_docs_files": len(docs_files),
                "total_source_files": len(source_files),
                "total_python_modules": len(python_modules),
                "packages": sorted(packages_set),
                "file_type_distribution": file_type_dist,
            },
            "docs_files": docs_files,
            "source_files": source_files,
        }

        # Write output
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(inventory, indent=2, ensure_ascii=False), encoding="utf-8")

        total = len(docs_files) + len(source_files)
        return ActionResult(
            status="APPROVED",
            remark=f"Scanned codebase: {len(docs_files)} docs files, {len(source_files)} source files ({len(python_modules)} Python modules) across {len(packages_set)} packages. Total {total} files.",
            artifacts={"CODEBASE_INVENTORY": str(output_path)},
        )

    except (TypeError, ValueError) as e:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to serialize inventory JSON: {e}",
            artifacts={},
            reject_code="SERIALIZATION_ERROR",
        )
    except OSError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"File system error writing inventory: {e}",
            artifacts={},
            reject_code="FILE_SYSTEM_ERROR",
        )


# ---------------------------------------------------------------------------
# Action: build_import_graph
# ---------------------------------------------------------------------------

@action("build_import_graph")
def build_import_graph(*, context: dict, state: dict, step_cfg: dict, project_root: Any) -> ActionResult:
    """Parse Python source files using AST, extract imports, build directed dependency graph with cycle detection."""
    project_root = Path(project_root)

    # Resolve input path
    inventory_path_str = context.get("CODEBASE_INVENTORY")
    if not inventory_path_str:
        return ActionResult(
            status="REJECTED",
            remark="CODEBASE_INVENTORY path not found in context",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    inventory_path = Path(inventory_path_str)
    if not inventory_path.exists():
        return ActionResult(
            status="REJECTED",
            remark=f"CODEBASE_INVENTORY file not found: {inventory_path}",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    # Parse inventory JSON
    try:
        inventory_text = inventory_path.read_text(encoding="utf-8")
        inventory = json.loads(inventory_text)
    except json.JSONDecodeError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"CODEBASE_INVENTORY is not valid JSON: {e}",
            artifacts={},
            reject_code="INVALID_STRUCTURE",
        )
    except OSError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"Could not read CODEBASE_INVENTORY: {e}",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    # Validate structure
    if "source_files" not in inventory or not isinstance(inventory["source_files"], list):
        return ActionResult(
            status="REJECTED",
            remark="CODEBASE_INVENTORY does not contain a valid 'source_files' array",
            artifacts={},
            reject_code="INVALID_STRUCTURE",
        )

    # Filter Python files
    python_files = [f for f in inventory["source_files"] if f.get("file_type") == "python"]
    if not python_files:
        return ActionResult(
            status="REJECTED",
            remark="No Python files found in CODEBASE_INVENTORY",
            artifacts={},
            reject_code="NO_PYTHON_FILES",
        )

    # Resolve output path
    output_path_str = context.get("IMPORT_GRAPH")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="IMPORT_GRAPH output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )
    output_path = Path(output_path_str)

    try:
        # Build module registry: absolute_path -> fully qualified module name
        module_registry: dict[str, str] = {}
        for f in python_files:
            abs_path = f.get("absolute_path", "")
            pkg_path = f.get("package_path", "")
            if abs_path and pkg_path:
                module_registry[abs_path] = pkg_path

        # Parse each Python file for imports
        edges: list[dict[str, Any]] = []
        parse_errors: list[dict[str, str]] = []
        all_modules: set[str] = set()
        adjacency: dict[str, list[str]] = {}

        for f in python_files:
            abs_path = f.get("absolute_path", "")
            rel_path = f.get("relative_path", "")
            pkg_path = f.get("package_path", "")

            if not abs_path or not pkg_path:
                continue

            all_modules.add(pkg_path)
            if pkg_path not in adjacency:
                adjacency[pkg_path] = []

            # Read and parse the file
            source_path = Path(abs_path)
            if not source_path.exists():
                parse_errors.append({
                    "file": rel_path,
                    "error": "File not found on disk",
                })
                continue

            content = _read_text_safe(source_path)
            if content is None:
                parse_errors.append({
                    "file": rel_path,
                    "error": "Could not read file (encoding error)",
                })
                continue

            try:
                tree = ast.parse(content, filename=abs_path)
            except SyntaxError as e:
                parse_errors.append({
                    "file": rel_path,
                    "error": f"Syntax error: {e}",
                })
                continue

            # Walk AST for imports
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        target = alias.name
                        edges.append({
                            "source": pkg_path,
                            "target": target,
                            "import_type": "absolute",
                            "imported_names": [alias.name],
                            "line_number": node.lineno,
                        })
                        all_modules.add(target)
                        adjacency[pkg_path].append(target)
                        if target not in adjacency:
                            adjacency[target] = []

                elif isinstance(node, ast.ImportFrom):
                    level = node.level or 0
                    module = node.module or ""
                    imported_names = [alias.name for alias in node.names]

                    if level > 0:
                        # Relative import
                        resolved = _resolve_relative_import(level, module if module else None, pkg_path)
                        if resolved is not None:
                            edges.append({
                                "source": pkg_path,
                                "target": resolved,
                                "import_type": "relative",
                                "imported_names": imported_names,
                                "line_number": node.lineno,
                            })
                            all_modules.add(resolved)
                            adjacency[pkg_path].append(resolved)
                            if resolved not in adjacency:
                                adjacency[resolved] = []
                        else:
                            edges.append({
                                "source": pkg_path,
                                "target": "<unresolved>",
                                "import_type": "relative",
                                "imported_names": imported_names,
                                "line_number": node.lineno,
                            })
                    else:
                        # Absolute import: from X import Y
                        if module:
                            target = module
                            edges.append({
                                "source": pkg_path,
                                "target": target,
                                "import_type": "absolute",
                                "imported_names": imported_names,
                                "line_number": node.lineno,
                            })
                            all_modules.add(target)
                            adjacency[pkg_path].append(target)
                            if target not in adjacency:
                                adjacency[target] = []

        # Check if all files failed to parse
        successfully_parsed = len(python_files) - len(parse_errors)
        if successfully_parsed == 0 and parse_errors:
            return ActionResult(
                status="REJECTED",
                remark=f"All {len(python_files)} Python files failed to parse",
                artifacts={},
                reject_code="ALL_FILES_UNPARSEABLE",
            )

        # Compute per-module metrics
        fan_out: dict[str, int] = {}
        fan_in: dict[str, int] = {}
        for mod in all_modules:
            fan_out[mod] = 0
            fan_in[mod] = 0

        for edge in edges:
            src = edge["source"]
            tgt = edge["target"]
            if tgt == "<unresolved>":
                continue
            fan_out[src] = fan_out.get(src, 0) + 1
            fan_in[tgt] = fan_in.get(tgt, 0) + 1

        # Detect cycles
        cycles = _detect_cycles(adjacency)

        # Build node list
        nodes = []
        for mod in sorted(all_modules):
            # Find the file_path for this module
            file_path = ""
            for f in python_files:
                if f.get("package_path") == mod:
                    file_path = f.get("relative_path", "")
                    break
            nodes.append({
                "module": mod,
                "file_path": file_path,
                "fan_in": fan_in.get(mod, 0),
                "fan_out": fan_out.get(mod, 0),
            })

        # Assemble output
        graph_data = {
            "metadata": {
                "total_modules": len(all_modules),
                "total_edges": len(edges),
                "total_cycles": len(cycles),
                "graph_timestamp": datetime.now(timezone.utc).isoformat(),
            },
            "nodes": nodes,
            "edges": edges,
            "cycles": [
                {"length": len(c) - 1, "modules": c}
                for c in cycles
            ],
        }

        if parse_errors:
            graph_data["parse_errors"] = parse_errors

        # Write output
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(graph_data, indent=2, ensure_ascii=False), encoding="utf-8")

        return ActionResult(
            status="APPROVED",
            remark=f"Built import graph: {len(all_modules)} modules, {len(edges)} edges, {len(cycles)} cycles detected. {len(parse_errors)} files had parse errors.",
            artifacts={"IMPORT_GRAPH": str(output_path)},
        )

    except MemoryError:
        return ActionResult(
            status="REJECTED",
            remark="Memory exhausted while building import graph",
            artifacts={},
            reject_code="RESOURCE_EXHAUSTED",
        )
    except (TypeError, ValueError) as e:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to serialize import graph JSON: {e}",
            artifacts={},
            reject_code="SERIALIZATION_ERROR",
        )
    except OSError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"File system error: {e}",
            artifacts={},
            reject_code="FILE_SYSTEM_ERROR",
        )


# ---------------------------------------------------------------------------
# Action: validate_intelligence_outputs
# ---------------------------------------------------------------------------

@action("validate_intelligence_outputs")
def validate_intelligence_outputs(*, context: dict, state: dict, step_cfg: dict, project_root: Any) -> ActionResult:
    """Validate all generated intelligence reports for structural completeness, evidence backing, self-containment, and cross-report consistency."""
    project_root = Path(project_root)

    # Resolve all 4 input artifact paths
    input_keys = [
        "AUDIENCE_META_FILE",
        "HEALTH_FINDINGS_FILE",
        "SECURITY_FINDINGS_FILE",
        "FINDINGS_REPORT_FILE",
    ]
    input_contents: dict[str, str] = {}
    input_paths: dict[str, Path] = {}

    for key in input_keys:
        path_str = context.get(key)
        if not path_str:
            return ActionResult(
                status="REJECTED",
                remark=f"Missing artifact path in context: {key}",
                artifacts={},
                reject_code="MISSING_ARTIFACT",
            )
        p = Path(path_str)
        if not p.exists():
            return ActionResult(
                status="REJECTED",
                remark=f"Artifact file not found for {key}: {p}",
                artifacts={},
                reject_code="MISSING_ARTIFACT",
            )
        input_paths[key] = p

    # Resolve output path
    output_path_str = context.get("VALIDATION_REPORT_FILE")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="VALIDATION_REPORT_FILE output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )
    output_path = Path(output_path_str)

    # Read all input files
    for key in input_keys:
        p = input_paths[key]
        try:
            content = p.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            try:
                content = p.read_text(encoding="latin-1")
            except Exception:
                content = ""
        except OSError:
            content = ""
        input_contents[key] = content

    # Run validation checks
    checks: list[dict[str, Any]] = []

    # Individual file validations
    summary_data: dict[str, dict[str, Any]] = {}
    for key in input_keys:
        content = input_contents[key]
        short_key = key.lower()

        # Existence check (file exists and is non-empty)
        exists = len(content.strip()) > 0
        checks.append({
            "check_id": f"{key}_EXISTS",
            "target": key,
            "status": "PASS" if exists else "FAIL",
            "detail": f"File exists and is non-empty" if exists else f"File is empty or unreadable: {key}",
        })

        if exists:
            # Validate markdown structure
            validation = _validate_markdown_content(content)
            summary_data[short_key] = validation

            checks.append({
                "check_id": f"{key}_HAS_HEADINGS",
                "target": key,
                "status": "PASS" if validation["has_headings"] else "FAIL",
                "detail": "Contains at least one Markdown heading" if validation["has_headings"] else "No Markdown headings found",
            })

            checks.append({
                "check_id": f"{key}_HAS_EVIDENCE",
                "target": key,
                "status": "PASS" if validation["has_evidence"] else "FAIL",
                "detail": "Contains file path references, inline code, or fenced code blocks" if validation["has_evidence"] else "No evidence markers found (file paths, code blocks, inline code)",
            })

            checks.append({
                "check_id": f"{key}_SELF_CONTAINED",
                "target": key,
                "status": "PASS" if validation["self_contained"] else "FAIL",
                "detail": "Document is self-contained without dangling references" if validation["self_contained"] else "Contains dangling references (see above, see previous section, etc.)",
            })
        else:
            summary_data[short_key] = {
                "exists": False,
                "has_headings": False,
                "has_evidence": False,
                "self_contained": False,
            }

    # Cross-report validation for FINDINGS_REPORT_FILE
    findings_content = input_contents.get("FINDINGS_REPORT_FILE", "")
    health_content = input_contents.get("HEALTH_FINDINGS_FILE", "")
    security_content = input_contents.get("SECURITY_FINDINGS_FILE", "")

    # Check if findings report references health findings
    cross_ref_health = False
    if findings_content and health_content:
        # Look for references to health-related terms or finding IDs
        health_indicators = ["health", "H-", "circular", "coupling", "dead code", "complexity", "import discipline"]
        cross_ref_health = any(
            indicator.lower() in findings_content.lower()
            for indicator in health_indicators
        )

    checks.append({
        "check_id": "FINDINGS_REPORT_CROSS_REF_HEALTH",
        "target": "FINDINGS_REPORT_FILE",
        "status": "PASS" if cross_ref_health else "FAIL",
        "detail": "Findings report references health analysis content" if cross_ref_health else "Findings report does not appear to reference health analysis",
    })

    # Check if findings report references security findings
    cross_ref_security = False
    if findings_content and security_content:
        security_indicators = ["security", "S-", "secret", "vulnerability", "auth", "injection", "dependency"]
        cross_ref_security = any(
            indicator.lower() in findings_content.lower()
            for indicator in security_indicators
        )

    checks.append({
        "check_id": "FINDINGS_REPORT_CROSS_REF_SECURITY",
        "target": "FINDINGS_REPORT_FILE",
        "status": "PASS" if cross_ref_security else "FAIL",
        "detail": "Findings report references security analysis content" if cross_ref_security else "Findings report does not appear to reference security analysis",
    })

    # Compute overall status
    total_checks = len(checks)
    passed = sum(1 for c in checks if c["status"] == "PASS")
    failed = total_checks - passed
    overall = "PASS" if failed == 0 else "FAIL"

    # Build summary with correct key mapping
    summary_output = {}
    key_map = {
        "audience_meta_file": "audience_meta",
        "health_findings_file": "health_findings",
        "security_findings_file": "security_findings",
        "findings_report_file": "findings_report",
    }
    for full_key, short_key in key_map.items():
        data = summary_data.get(full_key, {
            "exists": False,
            "has_headings": False,
            "has_evidence": False,
            "self_contained": False,
        })
        entry = dict(data)
        if short_key == "findings_report":
            entry["cross_references_health"] = cross_ref_health
            entry["cross_references_security"] = cross_ref_security
        summary_output[short_key] = entry

    # Assemble validation report
    validation_report = {
        "validation_timestamp": datetime.now(timezone.utc).isoformat(),
        "overall_status": overall,
        "total_checks": total_checks,
        "passed_checks": passed,
        "failed_checks": failed,
        "checks": checks,
        "summary": summary_output,
    }

    # Write output
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(validation_report, indent=2, ensure_ascii=False), encoding="utf-8")
    except OSError as e:
        return ActionResult(
            status="REJECTED",
            remark=f"Could not write validation report: {e}",
            artifacts={},
            reject_code="FILE_SYSTEM_ERROR",
        )

    if overall == "PASS":
        remark = f"Validation passed: {passed}/{total_checks} checks passed. All reports are structurally sound."
    else:
        remark = f"Validation completed with failures: {passed}/{total_checks} checks passed, {failed} failed. See validation report for details."

    return ActionResult(
        status="APPROVED",
        remark=remark,
        artifacts={"VALIDATION_REPORT_FILE": str(output_path)},
    )
