"""Domain actions for text_summarizer_ayz.

Auto-generated by AGB v3. Implements domain-specific action functions.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from agent_runner_v2.action_result import ActionResult
from agent_runner_v2.workflow_packages.actions import action


@action("parse_input_document")
def parse_input_document(
    *, context: dict, state: dict, step_cfg: dict, project_root: Any
) -> ActionResult:
    """Parse a source document (.txt, .md, .pdf, or .docx) into a structured JSON representation."""
    project_root = Path(project_root)

    # --- Resolve input path ---
    input_path_str = context.get("SOURCE_DOCUMENT_FILE")
    if not input_path_str:
        return ActionResult(
            status="REJECTED",
            remark="SOURCE_DOCUMENT_FILE path not found in context",
            artifacts={},
            reject_code="MISSING_INPUT_PATH",
        )

    source_path = Path(input_path_str)
    if not source_path.is_file():
        return ActionResult(
            status="REJECTED",
            remark=f"Source document not found at {source_path}",
            artifacts={},
            reject_code="FILE_NOT_FOUND",
        )

    # --- Resolve output path ---
    output_path_str = context.get("PARSED_DOCUMENT")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="PARSED_DOCUMENT output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )
    output_path = Path(output_path_str)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # --- Validate file extension ---
    ext = source_path.suffix.lower()
    supported_extensions = {".txt", ".md", ".pdf", ".docx"}
    if ext not in supported_extensions:
        return ActionResult(
            status="REJECTED",
            remark=f"Unsupported file extension '{ext}'. Supported: {', '.join(sorted(supported_extensions))}",
            artifacts={},
            reject_code="UNSUPPORTED_FORMAT",
        )

    # --- Extract text content based on format ---
    text_content = ""
    try:
        if ext in (".txt", ".md"):
            try:
                text_content = source_path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                text_content = source_path.read_text(encoding="latin-1")
            except PermissionError:
                return ActionResult(
                    status="REJECTED",
                    remark=f"Permission denied reading file: {source_path}",
                    artifacts={},
                    reject_code="FILE_READ_ERROR",
                )
            except OSError as exc:
                return ActionResult(
                    status="REJECTED",
                    remark=f"Error reading file: {exc}",
                    artifacts={},
                    reject_code="FILE_READ_ERROR",
                )

        elif ext == ".pdf":
            try:
                import PyPDF2
            except ImportError:
                return ActionResult(
                    status="REJECTED",
                    remark="PyPDF2 library is required for PDF parsing but is not installed",
                    artifacts={},
                    reject_code="MISSING_DEPENDENCY",
                )
            try:
                page_texts = []
                with open(source_path, "rb") as pdf_file:
                    reader = PyPDF2.PdfReader(pdf_file)
                    for page in reader.pages:
                        page_text = page.extract_text()
                        if page_text:
                            page_texts.append(page_text)
                text_content = "\n\n".join(page_texts)
            except Exception as exc:
                return ActionResult(
                    status="REJECTED",
                    remark=f"PDF extraction failed: {exc}",
                    artifacts={},
                    reject_code="EXTRACTION_FAILED",
                )

        elif ext == ".docx":
            try:
                import docx
            except ImportError:
                return ActionResult(
                    status="REJECTED",
                    remark="python-docx library is required for DOCX parsing but is not installed",
                    artifacts={},
                    reject_code="MISSING_DEPENDENCY",
                )
            try:
                document = docx.Document(str(source_path))
                paragraphs = [para.text for para in document.paragraphs]
                text_content = "\n".join(paragraphs)
            except Exception as exc:
                return ActionResult(
                    status="REJECTED",
                    remark=f"DOCX extraction failed: {exc}",
                    artifacts={},
                    reject_code="EXTRACTION_FAILED",
                )

    except Exception as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Unexpected error during extraction: {exc}",
            artifacts={},
            reject_code="EXTRACTION_FAILED",
        )

    # --- Validate non-empty content ---
    stripped = text_content.strip()
    if not stripped:
        return ActionResult(
            status="REJECTED",
            remark="Extracted text content is empty after parsing",
            artifacts={},
            reject_code="EMPTY_DOCUMENT",
        )

    # --- Normalize whitespace but preserve paragraph boundaries ---
    lines = stripped.splitlines()
    normalized_lines = []
    for line in lines:
        normalized_lines.append(" ".join(line.split()))
    normalized_text = "\n".join(normalized_lines)

    # --- Compute metrics ---
    words = normalized_text.split()
    word_count = len(words)

    paragraphs = [p.strip() for p in normalized_text.split("\n") if p.strip()]
    paragraph_count = len(paragraphs)

    format_label = ext.lstrip(".")

    # --- Build output JSON ---
    parsed_data = {
        "content": normalized_text,
        "metadata": {
            "format": format_label,
            "source_file": source_path.name,
            "word_count": word_count,
            "paragraph_count": paragraph_count,
        },
    }

    # --- Write output ---
    try:
        output_path.write_text(json.dumps(parsed_data, indent=2, ensure_ascii=False), encoding="utf-8")
    except OSError as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to write parsed document: {exc}",
            artifacts={},
            reject_code="WRITE_FAILED",
        )

    return ActionResult(
        status="APPROVED",
        remark=f"Parsed {format_label} document: {word_count} words, {paragraph_count} paragraphs",
        artifacts={"PARSED_DOCUMENT": str(output_path)},
    )


@action("render_prose_output")
def render_prose_output(
    *, context: dict, state: dict, step_cfg: dict, project_root: Any
) -> ActionResult:
    """Format the transformed summary content as a Markdown document and write it to the output artifact path."""
    project_root = Path(project_root)

    # --- Resolve input path ---
    input_path_str = context.get("TRANSFORMED_CONTENT")
    if not input_path_str:
        return ActionResult(
            status="REJECTED",
            remark="TRANSFORMED_CONTENT path not found in context",
            artifacts={},
            reject_code="MISSING_INPUT_PATH",
        )

    input_path = Path(input_path_str)
    if not input_path.is_file():
        return ActionResult(
            status="REJECTED",
            remark=f"TRANSFORMED_CONTENT file not found at {input_path}",
            artifacts={},
            reject_code="MISSING_INPUT",
        )

    # --- Resolve output path ---
    output_path_str = context.get("OUTPUT_FILE")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="OUTPUT_FILE output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )
    output_path = Path(output_path_str)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # --- Load and validate JSON ---
    try:
        raw = input_path.read_text(encoding="utf-8")
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Invalid JSON in TRANSFORMED_CONTENT: {exc}",
            artifacts={},
            reject_code="INVALID_CONTENT",
        )
    except OSError as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to read TRANSFORMED_CONTENT: {exc}",
            artifacts={},
            reject_code="MISSING_INPUT",
        )

    # --- Validate required fields ---
    required_fields = ["summary_text", "word_count", "source_word_count"]
    missing = [f for f in required_fields if f not in data]
    if missing:
        return ActionResult(
            status="REJECTED",
            remark=f"Missing required fields in TRANSFORMED_CONTENT: {', '.join(missing)}",
            artifacts={},
            reject_code="INVALID_CONTENT",
        )

    summary_text = data["summary_text"]
    summary_word_count = data["word_count"]
    source_word_count = data["source_word_count"]
    language = data.get("language", "unknown")

    # --- Compute compression ratio ---
    if source_word_count > 0:
        compression_ratio = summary_word_count / source_word_count
    else:
        compression_ratio = 0.0

    # --- Build Markdown document ---
    md_lines = [
        "# Summary",
        "",
        f"**Source word count:** {source_word_count}",
        f"**Summary word count:** {summary_word_count}",
        f"**Compression ratio:** {compression_ratio:.1%}",
        f"**Language:** {language}",
        "",
        "---",
        "",
        summary_text,
        "",
    ]
    markdown_content = "\n".join(md_lines)

    # --- Write output ---
    try:
        output_path.write_text(markdown_content, encoding="utf-8")
    except OSError as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to write output file: {exc}",
            artifacts={},
            reject_code="WRITE_FAILED",
        )

    return ActionResult(
        status="APPROVED",
        remark=f"Rendered prose summary: {summary_word_count}/{source_word_count} words ({compression_ratio:.1%} compression)",
        artifacts={"OUTPUT_FILE": str(output_path)},
    )
