"""Domain actions for agentic_workflow_builder.

Auto-generated by AGB v3. Implements domain-specific action functions.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from agent_runner_v2.action_result import ActionResult
from agent_runner_v2.workflow_packages.actions import action


# ---------------------------------------------------------------------------
# Shared parsing helpers
# ---------------------------------------------------------------------------

def _read_file_with_fallback(path: Path) -> str | None:
    """Read a text file with UTF-8 primary and latin-1 fallback."""
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        try:
            return path.read_text(encoding="latin-1")
        except Exception:
            return None


def _parse_yaml_frontmatter(text: str) -> dict[str, str]:
    """Extract simple key:value pairs from YAML frontmatter delimited by ---."""
    result: dict[str, str] = {}
    match = re.search(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not match:
        return result
    block = match.group(1)
    for line in block.splitlines():
        line = line.strip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip().strip("\"'")
        if key:
            result[key] = value
    return result


def _find_heading_section(lines: list[str], heading_pattern: re.Pattern) -> tuple[int, int, str]:
    """Find a heading matching a pattern. Returns (start_idx, end_idx, heading_line).

    end_idx is the index of the next heading of equal or higher level, or len(lines).
    """
    start = -1
    heading_line = ""
    heading_level = 0
    for i, line in enumerate(lines):
        m = re.match(r"^(#{1,6})\s+(.*)", line)
        if m:
            level = len(m.group(1))
            title = m.group(2).strip()
            if start == -1 and heading_pattern.search(title):
                start = i
                heading_line = title
                heading_level = level
            elif start != -1 and level <= heading_level:
                return start, i, heading_line
    if start != -1:
        return start, len(lines), heading_line
    return -1, -1, ""


def _collect_subsections(lines: list[str], start: int, end: int) -> dict[str, list[str]]:
    """Collect sub-headings and their content within a range."""
    sections: dict[str, list[str]] = {}
    current_key = "__preamble__"
    sections[current_key] = []
    for i in range(start + 1, end):
        line = lines[i]
        m = re.match(r"^(#{2,6})\s+(.*)", line)
        if m:
            current_key = m.group(2).strip()
            sections[current_key] = []
        else:
            sections[current_key].append(line)
    return sections


def _extract_bullet_items(lines: list[str]) -> list[str]:
    """Extract bullet list items from lines."""
    items = []
    for line in lines:
        stripped = line.strip()
        m = re.match(r"^[-*]\s+(.*)", stripped)
        if m:
            items.append(m.group(1).strip())
        elif stripped.startswith("- ") or stripped.startswith("* "):
            items.append(stripped[2:].strip())
    return items


def _extract_markdown_table(lines: list[str]) -> list[dict[str, str]]:
    """Extract a markdown table into a list of dicts keyed by header names."""
    header_line = None
    separator_found = False
    rows: list[list[str]] = []

    for line in lines:
        stripped = line.strip()
        if not stripped or not stripped.startswith("|"):
            if header_line and separator_found and rows:
                break
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if header_line is None:
            header_line = cells
        elif not separator_found:
            if all(re.match(r"^[-:]+$", c) for c in cells):
                separator_found = True
            else:
                header_line = None
        elif separator_found:
            rows.append(cells)

    if not header_line or not separator_found:
        return []

    result = []
    for row in rows:
        entry = {}
        for idx, header in enumerate(header_line):
            entry[header] = row[idx] if idx < len(row) else ""
        result.append(entry)
    return result


def _extract_state_variables(text: str) -> list[dict[str, Any]]:
    """Extract backtick-quoted identifiers and detect assignment vs reference patterns."""
    variables: dict[str, dict[str, Any]] = {}

    for match in re.finditer(r"`([a-zA-Z_][a-zA-Z0-9_]*)`", text):
        var_name = match.group(1)
        if var_name not in variables:
            variables[var_name] = {
                "name": var_name,
                "assignments": [],
                "references": [],
            }

    for line_no, line in enumerate(text.splitlines(), 1):
        for match in re.finditer(r"`([a-zA-Z_][a-zA-Z0-9_]*)`", line):
            var_name = match.group(1)
            if var_name in variables:
                if re.search(rf"`{re.escape(var_name)}`\s*=", line) or re.search(rf"=\s*`{re.escape(var_name)}`", line):
                    variables[var_name]["assignments"].append(line_no)
                else:
                    variables[var_name]["references"].append(line_no)

    return list(variables.values())


def _extract_conditional_routing(text: str) -> list[dict[str, str]]:
    """Extract conditional routing patterns (English if...then and Chinese equivalents)."""
    routes: list[dict[str, str]] = []

    en_pattern = re.compile(
        r"if\s+(.+?)\s*(?:then|,)\s*(.+?)(?:\s*else\s*(.+))?$",
        re.IGNORECASE | re.MULTILINE,
    )
    for match in en_pattern.finditer(text):
        entry = {
            "condition": match.group(1).strip(),
            "then_branch": match.group(2).strip(),
            "else_branch": match.group(3).strip() if match.group(3) else "",
            "type": "english_conditional",
        }
        routes.append(entry)

    zh_pattern = re.compile(
        r"([\u4e00-\u9fff].*?)(?:\u5982\u679c|\u82e5)(.+?)(?:\u5219|\u5c31)(.+?)(?:\u5426\u5219|\u53e6\u5219)(.*)",
        re.MULTILINE,
    )
    for match in zh_pattern.finditer(text):
        entry = {
            "condition": match.group(2).strip(),
            "then_branch": match.group(3).strip(),
            "else_branch": match.group(4).strip(),
            "type": "chinese_conditional",
        }
        routes.append(entry)

    zh_simple = re.compile(
        r"([\u4e00-\u9fff].*?)(?:\u5982\u679c|\u82e5)(.+?)(?:\u5219|\u5c31)(.+?)(?:\u3002|$)",
        re.MULTILINE,
    )
    for match in zh_simple.finditer(text):
        already_captured = any(
            r.get("condition") == match.group(2).strip() for r in routes
        )
        if not already_captured:
            entry = {
                "condition": match.group(2).strip(),
                "then_branch": match.group(3).strip(),
                "else_branch": "",
                "type": "chinese_conditional",
            }
            routes.append(entry)

    return routes


# ---------------------------------------------------------------------------
# Action 1: parse_jimeng_markdown
# ---------------------------------------------------------------------------

@action("parse_jimeng_markdown")
def parse_jimeng_markdown(*, context: dict, state: dict, step_cfg: dict, project_root: Any) -> ActionResult:
    """Parse a JiMeng-style agentic workflow markdown file into a structured JSON model."""
    project_root = Path(project_root)

    input_path_str = context.get("JIMENG_WORKFLOW_FILE")
    if not input_path_str:
        return ActionResult(
            status="REJECTED",
            remark="JIMENG_WORKFLOW_FILE path not found in context",
            artifacts={},
            reject_code="MISSING_INPUT_PATH",
        )

    input_path = Path(input_path_str)
    if not input_path.exists():
        return ActionResult(
            status="REJECTED",
            remark=f"JiMeng workflow file not found: {input_path}",
            artifacts={},
            reject_code="FILE_NOT_FOUND",
        )
    if not input_path.is_file():
        return ActionResult(
            status="REJECTED",
            remark=f"Path is not a regular file: {input_path}",
            artifacts={},
            reject_code="FILE_NOT_FOUND",
        )

    content = _read_file_with_fallback(input_path)
    if content is None:
        return ActionResult(
            status="REJECTED",
            remark=f"Cannot read JiMeng workflow file (encoding error): {input_path}",
            artifacts={},
            reject_code="FILE_READ_ERROR",
        )

    lines = content.splitlines()

    # --- 1. YAML frontmatter ---
    frontmatter = _parse_yaml_frontmatter(content)

    # --- 2. Role positioning ---
    role_pattern = re.compile(r"[\u89d2\u8272\u5b9a\u4f4d]|role|responsibility", re.IGNORECASE)
    role_start, role_end, role_heading = _find_heading_section(lines, role_pattern)
    role_info: dict[str, Any] = {"heading": role_heading, "responsibilities": [], "core_principles": []}
    if role_start >= 0:
        subsecs = _collect_subsections(lines, role_start, role_end)
        for key, sub_lines in subsecs.items():
            items = _extract_bullet_items(sub_lines)
            key_lower = key.lower()
            if any(kw in key_lower for kw in ["responsib", "\u804c\u8d23", "duty"]):
                role_info["responsibilities"] = items
            elif any(kw in key_lower for kw in ["principle", "\u539f\u5219", "core"]):
                role_info["core_principles"] = items
            elif key == "__preamble__" and items:
                role_info["responsibilities"] = items
        if not role_info["responsibilities"] and not role_info["core_principles"]:
            all_items = _extract_bullet_items(lines[role_start:role_end])
            if all_items:
                role_info["responsibilities"] = all_items

    # --- 3. Tool specification table ---
    tool_pattern = re.compile(r"\u5de5\u5177|tool\s*spec|tool\s*list", re.IGNORECASE)
    tool_start, tool_end, tool_heading = _find_heading_section(lines, tool_pattern)
    tools: list[dict[str, str]] = []
    if tool_start >= 0:
        table_rows = _extract_markdown_table(lines[tool_start:tool_end])
        if table_rows:
            tools = table_rows
        else:
            bullet_items = _extract_bullet_items(lines[tool_start:tool_end])
            for item in bullet_items:
                parts = item.split(":", 1)
                if len(parts) == 2:
                    tools.append({"name": parts[0].strip(), "description": parts[1].strip()})
                else:
                    tools.append({"name": item.strip(), "description": ""})

    # --- 4. Execution phases ---
    phase_pattern = re.compile(
        r"(?:phase|step|\u9636\u6bb5|\u6b65\u9aa4)\s*[\d一二三四五六七八九十]+",
        re.IGNORECASE,
    )
    phases: list[dict[str, Any]] = []
    for i, line in enumerate(lines):
        m = re.match(r"^(#{1,6})\s+(.*)", line)
        if m and phase_pattern.search(m.group(2)):
            level = len(m.group(1))
            phase_title = m.group(2).strip()
            phase_end = len(lines)
            for j in range(i + 1, len(lines)):
                jm = re.match(r"^(#{1,6})\s+(.*)", lines[j])
                if jm and len(jm.group(1)) <= level and not phase_pattern.search(jm.group(2)):
                    phase_end = j
                    break
                if jm and len(jm.group(1)) <= level and phase_pattern.search(jm.group(2)):
                    phase_end = j
                    break

            phase_lines = lines[i + 1 : phase_end]
            subsecs = _collect_subsections(lines, i, phase_end)

            phase_entry: dict[str, Any] = {
                "title": phase_title,
                "entry_conditions": [],
                "instructions": [],
                "expected_output": [],
                "next_phase_transition": "",
            }
            for key, sub_lines in subsecs.items():
                key_lower = key.lower()
                if any(kw in key_lower for kw in ["entry", "\u5165\u53e3", "\u524d\u7f6e", "condition", "pre"]):
                    phase_entry["entry_conditions"] = _extract_bullet_items(sub_lines) or [
                        l.strip() for l in sub_lines if l.strip()
                    ]
                elif any(kw in key_lower for kw in ["output", "\u8f93\u51fa", "result", "\u7ed3\u679c"]):
                    phase_entry["expected_output"] = _extract_bullet_items(sub_lines) or [
                        l.strip() for l in sub_lines if l.strip()
                    ]
                elif any(kw in key_lower for kw in ["next", "\u4e0b\u4e00", "transition", "\u8f6c\u6362"]):
                    text_content = "\n".join(l.strip() for l in sub_lines if l.strip())
                    phase_entry["next_phase_transition"] = text_content
                elif any(kw in key_lower for kw in ["instruction", "\u6307\u4ee4", "\u6b65\u9aa4", "\u64cd\u4f5c", "detail"]):
                    phase_entry["instructions"] = _extract_bullet_items(sub_lines) or [
                        l.strip() for l in sub_lines if l.strip()
                    ]

            if not phase_entry["instructions"]:
                all_bullets = _extract_bullet_items(phase_lines)
                if all_bullets:
                    phase_entry["instructions"] = all_bullets
                else:
                    phase_entry["instructions"] = [
                        l.strip() for l in phase_lines if l.strip()
                    ]

            phases.append(phase_entry)

    # --- 5. Configuration cards ---
    config_cards: list[dict[str, Any]] = []
    config_pattern = re.compile(r"generate_form_for_info_collection|config.*card|\u914d\u7f6e\u5361")
    for i, line in enumerate(lines):
        if config_pattern.search(line):
            nearest_heading = ""
            for j in range(i - 1, -1, -1):
                hm = re.match(r"^(#{1,6})\s+(.*)", lines[j])
                if hm:
                    nearest_heading = hm.group(2).strip()
                    break
            field_lines = []
            for j in range(i + 1, min(i + 50, len(lines))):
                if re.match(r"^#{1,6}\s+", lines[j]):
                    break
                field_lines.append(lines[j])
            fields = []
            for fl in field_lines:
                fl_stripped = fl.strip()
                if not fl_stripped or not fl_stripped.startswith(("-", "*")):
                    continue
                field_text = re.sub(r"^[-*]\s*", "", fl_stripped)
                required = "\u5fc5\u586b" in field_text or "required" in field_text.lower()
                optional = "\u53ef\u9009" in field_text or "optional" in field_text.lower()
                default_match = re.search(r"(?:default|defaults to|\u9ed8\u8ba4\u503c)[:\s=]*(.+?)(?:[,;.]|$)", field_text, re.IGNORECASE)
                default_val = default_match.group(1).strip() if default_match else None
                dynamic_match = re.search(r"(?:dynamic|dynamic_options|\u52a8\u6001\u9009\u9879)[:\s=]*(.+?)(?:[,;.]|$)", field_text, re.IGNORECASE)
                dynamic_rule = dynamic_match.group(1).strip() if dynamic_match else None
                fields.append({
                    "description": field_text,
                    "required": required,
                    "optional": optional,
                    "default": default_val,
                    "dynamic_options": dynamic_rule,
                })
            config_cards.append({
                "associated_phase": nearest_heading,
                "trigger": line.strip(),
                "fields": fields,
            })

    # --- 6. Embedded prompts ---
    embedded_prompts: list[dict[str, str]] = []
    prompt_heading_pattern = re.compile(
        r"(?:director|assistant|prompt|\u5bfc\u6f14|\u52a9\u624b|\u63d0\u793a\u8bcd|\u89d2\u8272\u63d0\u793a)",
        re.IGNORECASE,
    )
    i = 0
    while i < len(lines):
        m = re.match(r"^(#{1,6})\s+(.*)", lines[i])
        if m and prompt_heading_pattern.search(m.group(2)):
            level = len(m.group(1))
            heading_title = m.group(2).strip()
            prompt_lines = []
            j = i + 1
            for j in range(i + 1, len(lines)):
                jm = re.match(r"^(#{1,6})\s+(.*)", lines[j])
                if jm and len(jm.group(1)) <= level:
                    break
                prompt_lines.append(lines[j])
            prompt_text = "\n".join(prompt_lines).strip()
            if prompt_text:
                embedded_prompts.append({
                    "role": heading_title,
                    "prompt_text": prompt_text,
                })
            i = j if j < len(lines) else len(lines)
        else:
            i += 1

    # --- 7. State variables ---
    state_variables = _extract_state_variables(content)

    # --- 8. Conditional routing ---
    conditional_routing = _extract_conditional_routing(content)

    # --- 9. Quality criteria ---
    quality_pattern = re.compile(r"quality|validation|check|\u8d28\u91cf|\u6821\u9a8c|\u68c0\u67e5", re.IGNORECASE)
    quality_start, quality_end, quality_heading = _find_heading_section(lines, quality_pattern)
    quality_criteria: list[dict[str, str]] = []
    if quality_start >= 0:
        table_rows = _extract_markdown_table(lines[quality_start:quality_end])
        if table_rows:
            quality_criteria = table_rows
        else:
            for item in _extract_bullet_items(lines[quality_start:quality_end]):
                quality_criteria.append({"criterion": item})

    # --- 10. Prohibited behaviors ---
    prohibited_pattern = re.compile(r"prohibited|forbidden|\u7981\u6b62|\u4e0d\u5141\u8bb8|\u4e0d\u53ef", re.IGNORECASE)
    prohibited_start, prohibited_end, prohibited_heading = _find_heading_section(lines, prohibited_pattern)
    prohibited_behaviors: list[str] = []
    if prohibited_start >= 0:
        prohibited_behaviors = _extract_bullet_items(lines[prohibited_start:prohibited_end])
        if not prohibited_behaviors:
            prohibited_behaviors = [
                l.strip() for l in lines[prohibited_start:prohibited_end] if l.strip()
            ]

    # --- Structural validation: at least one JiMeng element found ---
    has_structure = any([
        frontmatter,
        role_info["heading"],
        tools,
        phases,
        config_cards,
        embedded_prompts,
    ])
    if not has_structure:
        return ActionResult(
            status="REJECTED",
            remark="No recognizable JiMeng structure found in the input file",
            artifacts={},
            reject_code="INVALID_JIMENG_FORMAT",
        )

    # --- Build output JSON ---
    parsed_model = {
        "frontmatter": frontmatter,
        "role_positioning": role_info,
        "tool_specifications": tools,
        "execution_phases": phases,
        "configuration_cards": config_cards,
        "embedded_prompts": embedded_prompts,
        "state_variables": state_variables,
        "conditional_routing": conditional_routing,
        "quality_criteria": quality_criteria,
        "prohibited_behaviors": prohibited_behaviors,
    }

    output_path_str = context.get("JIMENG_PARSED_MODEL")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="JIMENG_PARSED_MODEL output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )
    output_path = Path(output_path_str)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        output_path.write_text(
            json.dumps(parsed_model, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
    except Exception as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to write parsed model: {exc}",
            artifacts={},
            reject_code="WRITE_FAILED",
        )

    return ActionResult(
        status="APPROVED",
        remark=f"Parsed JiMeng markdown into structured model: {len(phases)} phases, {len(tools)} tools, {len(config_cards)} config cards, {len(embedded_prompts)} embedded prompts",
        artifacts={"JIMENG_PARSED_MODEL": str(output_path)},
    )


# ---------------------------------------------------------------------------
# Action 2: assemble_requirements
# ---------------------------------------------------------------------------

@action("assemble_requirements")
def assemble_requirements(*, context: dict, state: dict, step_cfg: dict, project_root: Any) -> ActionResult:
    """Scan WORKFLOW_STEP_DESIGN to determine external Python package dependencies and write requirements.txt."""
    project_root = Path(project_root)

    input_path_str = context.get("WORKFLOW_STEP_DESIGN")
    if not input_path_str:
        return ActionResult(
            status="REJECTED",
            remark="WORKFLOW_STEP_DESIGN path not found in context",
            artifacts={},
            reject_code="MISSING_INPUT_PATH",
        )

    input_path = Path(input_path_str)
    if not input_path.exists():
        return ActionResult(
            status="REJECTED",
            remark=f"WORKFLOW_STEP_DESIGN file not found: {input_path}",
            artifacts={},
            reject_code="MISSING_ARTIFACT",
        )

    try:
        step_design_text = input_path.read_text(encoding="utf-8")
        step_design = json.loads(step_design_text)
    except json.JSONDecodeError as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"WORKFLOW_STEP_DESIGN contains invalid JSON: {exc}",
            artifacts={},
            reject_code="INVALID_CONTENT",
        )
    except Exception as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Cannot read WORKFLOW_STEP_DESIGN: {exc}",
            artifacts={},
            reject_code="FILE_READ_ERROR",
        )

    # Collect external dependencies from step definitions
    STDLIB_MODULES = {
        "json", "pathlib", "re", "os", "sys", "shutil", "typing", "collections",
        "datetime", "functools", "itertools", "hashlib", "io", "math", "copy",
        "enum", "abc", "dataclasses", "textwrap", "string", "struct", "tempfile",
        "glob", "fnmatch", "csv", "xml", "html", "urllib", "http", "ftplib",
        "smtplib", "email", "logging", "unittest", "argparse", "subprocess",
        "threading", "multiprocessing", "pickle", "sqlite3", "zipfile", "tarfile",
        "gzip", "bz2", "lzma", "zlib", "contextlib", "warnings", "traceback",
        "inspect", "importlib", "pkgutil", "ast", "dis", "time", "calendar",
        "random", "statistics", "decimal", "fractions", "operator", "pprint",
        "reprlib", "bisect", "heapq", "queue", "types", "weakref", "array",
        "codecs", "unicodedata", "locale", "gettext", "signal", "socket",
        "ssl", "select", "selectors", "mmap", "ctypes", "concurrent",
        "asyncio", "secrets", "hmac", "base64", "binascii", "quopri",
        "uu", "difflib", "pdb", "profile", "timeit", "trace",
    }

    PLATFORM_MODULES = {"agent_runner_v2"}

    dependencies: set[str] = set()

    # Check step_sequence for declared dependencies
    step_sequence = step_design.get("step_sequence", [])
    for step_def in step_sequence:
        # Check for explicit "dependencies" or "required_packages"
        for dep_key in ("dependencies", "required_packages"):
            deps = step_def.get(dep_key, [])
            if isinstance(deps, list):
                for dep in deps:
                    if isinstance(dep, str):
                        dep = dep.strip()
                        if dep:
                            dependencies.add(dep)

        # Check for inline code snippets with import statements
        code_snippet = step_def.get("code_snippet", "") or step_def.get("inline_code", "")
        if isinstance(code_snippet, str) and code_snippet:
            for import_match in re.finditer(r"^(?:from|import)\s+([a-zA-Z_][a-zA-Z0-9_.]*)", code_snippet, re.MULTILINE):
                module_name = import_match.group(1).split(".")[0]
                if module_name not in STDLIB_MODULES and module_name not in PLATFORM_MODULES:
                    dependencies.add(module_name)

    # Check action step definitions for dependency hints
    action_steps = step_design.get("action_steps", [])
    if isinstance(action_steps, list):
        for step_def in action_steps:
            for dep_key in ("dependencies", "required_packages"):
                deps = step_def.get(dep_key, [])
                if isinstance(deps, list):
                    for dep in deps:
                        if isinstance(dep, str):
                            dep = dep.strip()
                            if dep:
                                dependencies.add(dep)

    # Write requirements.txt
    output_path_str = context.get("WORKFLOW_REQUIREMENTS_FILE")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="WORKFLOW_REQUIREMENTS_FILE output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )
    output_path = Path(output_path_str)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        if dependencies:
            sorted_deps = sorted(dependencies, key=str.lower)
            content = "\n".join(sorted_deps) + "\n"
        else:
            content = "# No external dependencies required -- all imports are from the Python standard library.\n"
        output_path.write_text(content, encoding="utf-8")
    except Exception as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to write requirements.txt: {exc}",
            artifacts={},
            reject_code="WRITE_FAILED",
        )

    dep_count = len(dependencies)
    return ActionResult(
        status="APPROVED",
        remark=f"Generated requirements.txt with {dep_count} external dependencies",
        artifacts={"WORKFLOW_REQUIREMENTS_FILE": str(output_path)},
    )
