"""Domain actions for key_points implementation of text_summarizer_ayz.

Auto-generated by AGB v3. Implements the render_key_points_output action override.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from agent_runner_v2.action_result import ActionResult
from agent_runner_v2.workflow_packages.actions import action


@action("render_key_points_output")
def render_key_points_output(
    *, context: dict, state: dict, step_cfg: dict, project_root: Any
) -> ActionResult:
    """Format the key points list as a numbered Markdown document with importance annotations."""
    project_root = Path(project_root)

    # --- Resolve input path ---
    input_path_str = context.get("TRANSFORMED_CONTENT")
    if not input_path_str:
        return ActionResult(
            status="REJECTED",
            remark="TRANSFORMED_CONTENT path not found in context",
            artifacts={},
            reject_code="MISSING_INPUT_PATH",
        )

    input_path = Path(input_path_str)
    if not input_path.is_file():
        return ActionResult(
            status="REJECTED",
            remark=f"TRANSFORMED_CONTENT file not found at {input_path}",
            artifacts={},
            reject_code="MISSING_INPUT",
        )

    # --- Resolve output path ---
    output_path_str = context.get("OUTPUT_FILE")
    if not output_path_str:
        return ActionResult(
            status="REJECTED",
            remark="OUTPUT_FILE output path not found in context",
            artifacts={},
            reject_code="MISSING_OUTPUT_PATH",
        )
    output_path = Path(output_path_str)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # --- Load and validate JSON ---
    try:
        raw = input_path.read_text(encoding="utf-8")
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Invalid JSON in TRANSFORMED_CONTENT: {exc}",
            artifacts={},
            reject_code="INVALID_CONTENT",
        )
    except OSError as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to read TRANSFORMED_CONTENT: {exc}",
            artifacts={},
            reject_code="MISSING_INPUT",
        )

    # --- Validate key_points structure ---
    if "key_points" not in data:
        return ActionResult(
            status="REJECTED",
            remark="Missing 'key_points' array in TRANSFORMED_CONTENT",
            artifacts={},
            reject_code="INVALID_STRUCTURE",
        )

    key_points = data["key_points"]
    if not isinstance(key_points, list):
        return ActionResult(
            status="REJECTED",
            remark="'key_points' must be an array",
            artifacts={},
            reject_code="INVALID_STRUCTURE",
        )

    if len(key_points) == 0:
        return ActionResult(
            status="REJECTED",
            remark="'key_points' array is empty",
            artifacts={},
            reject_code="INVALID_STRUCTURE",
        )

    # --- Validate each key point has required fields ---
    for idx, point in enumerate(key_points):
        if not isinstance(point, dict):
            return ActionResult(
                status="REJECTED",
                remark=f"Key point at index {idx} is not an object",
                artifacts={},
                reject_code="INVALID_STRUCTURE",
            )
        if "text" not in point:
            return ActionResult(
                status="REJECTED",
                remark=f"Key point at index {idx} missing 'text' field",
                artifacts={},
                reject_code="INVALID_STRUCTURE",
            )
        if "importance_score" not in point:
            return ActionResult(
                status="REJECTED",
                remark=f"Key point at index {idx} missing 'importance_score' field",
                artifacts={},
                reject_code="INVALID_STRUCTURE",
            )

    # --- Extract metadata ---
    source_word_count = data.get("source_word_count", 0)
    language = data.get("language", "unknown")
    total_key_points = data.get("total_key_points", len(key_points))

    # --- Build Markdown document ---
    md_lines = [
        "# Key Points",
        "",
        f"**Source word count:** {source_word_count}",
        f"**Total key points:** {total_key_points}",
        f"**Language:** {language}",
        "",
        "---",
        "",
    ]

    for idx, point in enumerate(key_points, start=1):
        text = point["text"]
        score = point["importance_score"]
        source_section = point.get("source_section", "unknown")
        md_lines.append(f"{idx}. [Score: {score}/10] {text} (from: {source_section})")
        md_lines.append("")

    markdown_content = "\n".join(md_lines)

    # --- Write output ---
    try:
        output_path.write_text(markdown_content, encoding="utf-8")
    except OSError as exc:
        return ActionResult(
            status="REJECTED",
            remark=f"Failed to write output file: {exc}",
            artifacts={},
            reject_code="WRITE_FAILED",
        )

    return ActionResult(
        status="APPROVED",
        remark=f"Rendered {total_key_points} key points from {source_word_count}-word source",
        artifacts={"OUTPUT_FILE": str(output_path)},
    )
