#!/usr/bin/env python3
from __future__ import annotations

"""
actions/publish_architecture_site.py - Publish the master documentation hub index.

This action generates the master index page that links to all audience-specific
documentation sites. The audience sites themselves are generated by their
respective workflows (51-55_*_docs_v1).
"""

import json
from pathlib import Path

from ..action_result import ActionResult
from ..architecture_site import render_master_index
from ..codebase_docs import build_snapshot
from ..constants import ARCHITECTURE_AUDIENCE_SITES, ARTIFACT_KEY_ARCHITECTURE_SITE_INDEX, ARTIFACT_KEY_ARCHITECTURE_SITE_MANIFEST, audience_site_artifacts
from ..doc_paths import docs_site_rel
from ..runtime_context import write_meta_sidecar


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def publish_architecture_site(*, context: dict[str, str], state: dict, step_cfg: dict, project_root: Path) -> ActionResult:
    mode = str(step_cfg.get("mode") or "publish")
    job_id = str(state.get("job_id") or "SITE")
    step = str(state.get("current_step") or "publish_architecture_site")
    meta_rel = (
        context.get("ARCHITECTURE_SITE_INDEX_METAJSON", "")
        or context.get("ARCHITECTURE_SITE_METAJSON", "")
    )

    snapshot = build_snapshot(
        project_root,
        mode=mode,
        job_id=job_id,
        step=step,
        workflow_name=str(state.get("template_group") or mode),
    )

    # Generate the master index site
    site_pages = render_master_index(snapshot, project_root)

    # Write all generated pages
    site_root = project_root / docs_site_rel()
    site_root.mkdir(parents=True, exist_ok=True)

    for rel_path, content in site_pages.items():
        _write_text(project_root / rel_path, content)

    # Write manifest (already included in site_pages from render_master_index)
    # But ensure it's written with correct path
    manifest_path = project_root / docs_site_rel("manifest.json")
    manifest = {
        "workflow": str(state.get("template_group") or mode),
        "generated_at": snapshot["generated_at"],
        "pages": sorted(site_pages.keys()),
        "index": docs_site_rel("index.html"),
        "audience_sites": [
            {"name": str(site["name"]).replace(" Documentation", ""), "path": f"{site['path']}index.html"}
            for site in ARCHITECTURE_AUDIENCE_SITES
        ],
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    site_artifacts = audience_site_artifacts()
    artifacts = {
        ARTIFACT_KEY_ARCHITECTURE_SITE_INDEX: site_artifacts[ARTIFACT_KEY_ARCHITECTURE_SITE_INDEX],
        ARTIFACT_KEY_ARCHITECTURE_SITE_MANIFEST: site_artifacts[ARTIFACT_KEY_ARCHITECTURE_SITE_MANIFEST],
    }

    if meta_rel:
        write_meta_sidecar(
            meta_rel,
            project_root=project_root,
            status="APPROVED",
            remark="Documentation hub index published.",
            artifacts=artifacts,
        )

    return ActionResult(
        status="APPROVED",
        remark="Documentation hub index published.",
        artifacts=artifacts,
    )
